### ISSUE TITLE
Dashboard not updated after renaming repo

### ISSUE THREAD

**Issue by joshq00** [gogits/gogs#1018]
The link on the dashboard always reflects the original repository name.

Steps to reproduce:

1. Create new repo **testproj**
2. Rename repo to **actual-proj**
3. Check dashboard

> **[user](#)** created repository **[user/testproj](#)**

which takes you to a 404

Thanks for this project. Gogs rocks! Can't wait for pull requests

**Comment by Unknwon** [comment]
Hi, thanks your feedback!

> user created repository user/testproj

I don't this should be updated, because you created as `user/testproj`

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:

**Comment by kasoki** [comment]
I think it should be updated since you're usually using the Dashboard as some kind of quick access to get to certain things. For instance after renaming a repository I can't even click on the commit hashes anymore since it redirects you to something like: domain.com/username/oldprojectname/commit/....

It's annoying and I really don't see a single reason to not fix this. @Unknwon reopen it please.

His example is probably bad since he only showed the create notification which really should stay like this, since as you've noted since he created it as user/testproj, but for every other interaction like opening issues, pushing commits etc. the links MUST be updated or it's just a huge mess.

**Comment by Unknwon** [comment]
@kasoki I've moved your request into https://github.com/gogits/gogs/issues/1566 .
