### ISSUE TITLE
Hardcoded user in ssh server

### ISSUE THREAD

**Issue by overnine** [gogits/gogs#1060]
https://github.com/gogits/gogs/blob/35c83f60266fb2178ae69db4b578dad333b6b2ea/modules/ssh/ssh.go#L59

**Comment by nicatronTg** [comment]
Looks more like a problem in accidentally leaving in test code than anything else.

**Comment by Unknwon** [comment]
Hmm... what does `WAT` mean?

**Comment by nicatronTg** [comment]
@Unknwon it's an English colloquialism for "what is happening?" or "why is this there?" It's usually used in exasperation or surprise due to something dramatically surprising. It's a derivative of the word "what" or the single phrase "what?"

The reason why the issue reporter posted this is because he wanted to either draw attention to the absolute path at the line referenced, or ask why there's an absolute path to a programmer's PC in there too.

**Comment by Unknwon** [comment]
@nicatronTg thanks for the explanation!

The file @overnine points to is completely not used in Gogs, but a prototype of builtin SSH server of Gogs. So don't worry about it :blush:

**Comment by nicatronTg** [comment]
@Unknwon of course :)

Keep it up! Gogs is quite nifty

**Comment by overnine** [comment]
http://i0.kym-cdn.com/photos/images/newsfeed/000/173/576/Wat8.jpg?1315930535

**Comment by rojaro** [comment]
![Wat.](https://s-media-cache-ak0.pinimg.com/736x/8a/30/89/8a30894b407ca6f08bdd7036010c2d2c.jpg)

**Comment by bashrc** [comment]
It's probably a good idea not to leave prototype code in the master branch.

**Comment by Unknwon** [comment]
@bashrc you're right, so we then made a `ssh` branch.

**Comment by Unknwon** [comment]
I'm closing it with the release, feel free to reopen it if you want to continue discussion. :smiley:
