### ISSUE TITLE
Clearer error message for illegal characters

### ISSUE THREAD

**Issue by martinellison** [gogits/gogs#1070]
I get this error from install. Admin user name is alphabetic.

GoGits · Version: 0.5.13.0212 Beta

**Comment by Unknwon** [comment]
We have docs for this: http://gogs.io/docs/intro/troubleshooting.html#form-validation

**Comment by martinellison** [comment]
Perhaps you could make the error message clearer.

**Comment by Unknwon** [comment]
True point, I'll mark this as enhancement.

**Comment by roberttstephens** [comment]
+1. I ran into this issue while installing yesterday. IMO, it would be better to tell the user that they tried to use a reserved word, instead of illegal characters. For example, none of the characters in 'admin' are disallowed.

The isLegalName (https://github.com/gogits/gogs/blob/master/models/repo.go#L259)[comment] and (https://github.com/gogits/gogs/blob/master/models/repo.go#L262)[for loop] have the same 'char' versus 'word' ambiguity.

IMO, it would be even better to tell the user which word or pattern they used. For example, "'Admin' is a reserved word and is not allowed". However, that could only be done by changing the function signature of repo.IsLegalName().

I'd be happy to submit a pull request in the next day or two if the core team is open to the idea.

**Comment by Unknwon** [comment]
@roberttstephens thanks for the info!

We can fix this in minutes, but it's good to leave chance to community in such cases.

Some hints:

- We start using a new pattern as shown in https://github.com/gogits/gogs/blob/develop/models/error.go
- You may want to add new code in line `#L10`, name a new type `ErrReservedWord`, then store corresponding pattern as a field `Pattern string`.

Ping me if you have any questions!

**Comment by Unknwon** [comment]
Hi @roberttstephens , do you still have time work on this?

**Comment by roberttstephens** [comment]
Hey @Unknwon . I didn't realize how many places use ErrRepoNameIllegal. Also the error handling pattern is unfamiliar to me. Therefore, I'm not sure how IsLegalName, the list of disallowed names and suffixes, and the error struct, function, and method should play together.

Maybe it's best if someone else takes this task?

**Comment by Unknwon** [comment]
@roberttstephens no worries! I can understand your concerns. Try next time :wink:

**Comment by Unknwon** [comment]
Hi @roberttstephens @martinellison , I've pushed code to `develop` and you can also test on https://try.gogs.io/user/sign_up . Gogs nows tells you which word is reserved or which pattern is not allowed.

**Comment by Unknwon** [comment]
Close as implemented, feel free to continue discussion! :smile:
