### ISSUE TITLE
Forking Broken?

### ISSUE THREAD

**Issue by iSDP** [gogits/gogs#1095]
V 0.5.13.0212 Beta

Clicking on the Fork button seems to do nothing....

**Comment by Unknwon** [comment]
Thanks your feedback!

It does nothing when you click on repository you owned, are you saying about this?

**Comment by iSDP** [comment]
Yes indeed


-------- Original Message --------

**Comment by tszym** [comment]
Hi,

May I add somme input about this one?

Here is the situation:
As a user, I am the owner of a public repository and am member (and creator) of an organization.

When I am on the page of the repo at `user/repo`, I want to fork it under the organization in order to get a `organization/repo` repository.
So I click on the *Fork* button, and there is nothing.

Hope it could help to fix it.

**Comment by iSDP** [comment]
I already said that haha

**Comment by tszym** [comment]
Just added some more details.

Also, I forgot this one: the installation I used to reproduce the problem is the `v0.6.1` binary release.

**Comment by iSDP** [comment]
It's a problem since 0.6.1

**Comment by iSDP** [comment]
0.6.0* at least.

**Comment by linquize** [comment]
I have no problem using gogs Version: 0.6.1.0327 Beta

**Comment by linquize** [comment]
I have no problem using gogs Version: 0.6.1.0327 Beta
I login user2.
I fork user1/repo1 into org1.

**Comment by tszym** [comment]
@linquize can you login as user1 (which I assume is in org1 and has rights to create and fork repos) and fork `user1/repo1` into org1?

**Comment by linquize** [comment]
But in previous test, user1 did not belong to org1

**Comment by linquize** [comment]
I understand the problem. You cannot fork your repo to your organization.
The fork button is no op.

**Comment by linquize** [comment]
If I transfer the repo to org1, gogs hangs. Need to restart gogs.
Transfer to a real user does not hang.

**Comment by Unknwon** [comment]
It is working now...
