### ISSUE TITLE
High memory usage for commits page

### ISSUE THREAD

**Issue by nuss-justin** [gogits/gogs#121]
I'm just playing with the 0.3 binaries in my free time and noticed that the memory usage starts to grow very fast when navigating to the commits page of a repo. The page itself often takes up to 10 seconds to load when having a larger repo, but the biggest problem is the memory not getting collected fast enough. After a few requests with my browser I got my memory usage to nearly 2GB and after around 30 minutes the memory is still at 600MB.

Here a screenshot from the stats after looking at a commits page:
![memstats](https://cloud.githubusercontent.com/assets/6443781/2794582/80885c8c-cbee-11e3-88b3-77a6e9521a49.PNG)

Here a screenshot from 12 minutes later:
![memstats_2](https://cloud.githubusercontent.com/assets/6443781/2794583/808ad156-cbee-11e3-933f-3f019c355780.PNG)

The repos I creating this memory usage are mirrors of torvalds/linux and gogits/gogs.

**Comment by icewheel** [comment]
I also pushed a big repository around ~450 MB. This results into high usage of memory around 1.79GB. After some it decreases to 1.1 GB and stuck there. I waited for half hour and no change in memory usage.
I tried to see the the difference of last commit using web but it took too long.
Than I deleted that repository and memory usage decreases to ~706MB. 

Even after deletion of repository through web memory usage is still same and its not freeing up memory. 
Also the few process like 'git diff' are running and they do not die even after repository is deleted.

This is after server is empty and do have any repository, all repo deleted.
./gogs web is eating up 330MB.
git diff shdf..............jhf3 is taking 439.8MB.

There are multiple 'git diff' processes running.

I am using version: 0.6.1.0325 Beta on Docker using image https://registry.hub.docker.com/_/docker-dev/

**Comment by icewheel** [comment]
![screenshot from 2015-06-06 06 15 55](https://cloud.githubusercontent.com/assets/6447642/8019265/8ab6e168-0c13-11e5-81a6-1bf5e5081f22.png)

Part 1: Simple commit via HTTPS
System Monitor Status

Server Uptime
    7 minutes, 9 seconds
Current Goroutines
    22
Current Memory Usage
    776MB
Total Memory Allocated
    1.1GB
Memory Obtained
    1.1GB
Pointer Lookup Times
    1655
Memory Allocate Times
    1090490
Memory Free Times
    927049
Current Heap Usage
    776MB
Heap Memory Obtained
    1.0GB
Heap Memory Idle
    259MB
Heap Memory In Use
    779MB
Heap Memory Released
    0B
Heap Objects
    163441
Bootstrap Stack Usage
    608KB
Stack Memory Obtained
    608KB
MSpan Structures Usage
    114KB
MSpan Structures Obtained
    1.0GB
MCache Structures Usage
    4.7KB
MCache Structures Obtained
    16KB
Profiling Bucket Hash Table Obtained
    1.4MB
GC Metadada Obtained
    65MB
Other System Allocation Obtained
    1.2MB
Next GC Recycle
    1.5GB
Since Last GC Time
    56.3s
Total GC Pause
    0.1s
Last GC Pause
    0.006s
GC Times
    33

Part 2: View the commit via WEB

System Monitor Status

Server Uptime
    9 minutes, 49 seconds
Current Goroutines
    22
Current Memory Usage
    114MB
Total Memory Allocated
    2.0GB
Memory Obtained
    1.1GB
Pointer Lookup Times
    13802
Memory Allocate Times
    1956911
Memory Free Times
    1711940
Current Heap Usage
    114MB
Heap Memory Obtained
    1.0GB
Heap Memory Idle
    921MB
Heap Memory In Use
    116MB
Heap Memory Released
    0B
Heap Objects
    244971
Bootstrap Stack Usage
    688KB
Stack Memory Obtained
    688KB
MSpan Structures Usage
    174KB
MSpan Structures Obtained
    1.0GB
MCache Structures Usage
    4.7KB
MCache Structures Obtained
    16KB
Profiling Bucket Hash Table Obtained
    1.4MB
GC Metadada Obtained
    65MB
Other System Allocation Obtained
    1.2MB
Next GC Recycle
    227MB
Since Last GC Time
    0.1s
Total GC Pause
    0.3s
Last GC Pause
    0.007s
GC Times
    49

**Comment by Unknwon** [comment]
@icewheel Huge push should normally push by SSH, HTTP needs time to GC.

But in your version there is a possible memory leak which should be fixed latest release, I recommend you upgrade and try it out.

**Comment by Unknwon** [comment]
Should checkout latest v0.7.6.

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by rafapolo** [comment]
Same error with "2017 Gogs Version: 0.11.19.0609"
output: https://pastebin.com/6G9AEaSN

**Comment by mckaygerhard** [comment]
still same problem for gogs 0.11 lasted
