### ISSUE TITLE
Post-Receive hook got a permission denied

### ISSUE THREAD

**Issue by minakolta** [gogits/gogs#1368]
I have a fresh installation of gogs, and i want to make an automated deployment.
2 branches staging and production, default user is unchanged "gogs"

in a post-receive script from gogs web interface

```
#!/bin/bash
id
ls -ashl /var/www/html/test

```

output 

uid=493(gogs) gid=494(gogs) groups=494(gogs)
remote: ls: cannot access /var/www/html/test: Permission denied

I got a permission denied of listing this directory, yet here is ssh listing as a sudor user

```
ls -ashl
4.0K drwxrwxr-x 3 developer server 4.0K Jul 15 19:41 .
4.0K drwxrwxr-x 7 developer server 4.0K Jul 15 17:55 ..
```
**gogs** is a member in **server** group and **developer** is a member in **gogs** group

**Comment by Unknwon** [comment]
Thanks your report!

> gogs is a member in server group and developer is a member in gogs group

Sorry I'm not pro on Linux user system, is this like `developer` belongs to `gogs`, and `gogs` belongs to `server` so `developer` belongs to `server` as well?

Can you check on the permission of `post-receive` hook under:

    path/to/repository/{username}/{reponame}.git/hooks/post-receive

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.

**Comment by t3nshi** [comment]
well I would appreciate some help on  this as well... In the above issue the user gogs should be able to write to /var/www/html/test since it had granted write perms for the group he belongs to (server) In my case it doesn't work even when the user reported on console is root (my gogs instance is being run by root user)
I should note that i'm trying to activate post-receive  through a git push over https.

Any help on this will be very much appreciated.

**Comment by t3nshi** [comment]
I will wait an answer... or should I open a new issue?

**Comment by Unknwon** [comment]
@t3nshi things are very different between now and 2015. I need more context of your words.
