### ISSUE TITLE
Incorrect handling of whitespaces in file names.

### ISSUE THREAD

**Issue by ZafiRUS** [gogits/gogs#1373]
In commit view page, all filenames with whitespaces are truncated, both in label and in link to file.
Like this: (file is named "Hello World.txt")
![gogs](https://cloud.githubusercontent.com/assets/388630/8763159/bbae681c-2d98-11e5-922a-b44283d1104b.PNG)

View file link is broken, but if you manually repair it, the file is there.

**Comment by joshcoody** [comment]
This also occurs if there are spaces in the folder names. 

It seems to only show the first word before a space, but it shouldn't care if there's a space or not.

**Comment by manfer** [comment]
This happens because the code that parses diff output has not filepaths with spaces into account. It splits on whitespaces and makes the asumption that it has correctly splitted the two paths in the diff header.

The file that contains the bug is `models/git_diff.go` and the bug is in the `ParsePatch` function when it begins to parse the diff header on line 169.

git diff header is like:

```diff --git a/path/to/file1 b/path/to/file2```

Splitting on spaces is not the correct way to parse that line if files or folders have spaces.

The next solution that comes to my mind would be to first remove `diff --git a/` and then split on ` b/` (with a space before the b).

This one should be trivial. Just changing line 82 to:

```const DIFF_HEAD = "diff --git a/"```

and line 174 to:

```fs := strings.Split(line[len(DIFF_HEAD):], " b/")```

Will be and enhancement but again will be not foolproof as `path/to/file1` could contain that sequence ` b/`.

So the only robust solution that comes to my mind is to get the filenames with another call to git diff.

`git diff -M -z --name-only`

and use the data from that command later when parsing the diff.

Or maybe the filenames can be parsed from the --- or +++ lines instead of from that `diff --git` header.

It is not trivial and not sure now exactly how to implement it. That's why I point to the bug just in case someone wants to try to code the solution.

Besides I'm maybe not taking every detail into account. So needs more work, more eyes and more ideas.

**Comment by Unknwon** [comment]
Closed by #1404
