### ISSUE TITLE
IP in HOST Setting ignored for Postgres Backend

### ISSUE THREAD

**Issue by eisensheng** [gogits/gogs#1400]
Setting the `HOST = 10.0.0.10:5433` for example and `DB_TYPE = postgres` leads to the error message 
```
[install.go:66 GlobalInit()] [E] Fail to initialize ORM engine: migrate: sync: dial tcp 127.0.0.1:5433: connection refused
````
It appears that the IP part of the HOST variable is ignored while changing the port number still has an effect.

This was observed with gogs compiled from archlinux aur gogs-git and the commit was 70d44e9565e372c73d4f0f42273d4899e8e07f75.

**Comment by Unknwon** [comment]
Thanks your feedback!

By 

> Setting the HOST = 10.0.0.10:5433 for example and DB_TYPE = postgres

Which file did you edit?

**Comment by eisensheng** [comment]
Thanks for your timely response. :wink: 

> Which file did you edit?

I've edited the file `/srv/gogs/conf/app.ini`. Except for the IP Address in `HOST` other settings like disabling registration were applied right away.

**Comment by manfer** [comment]
I think that config file is not supposed to be edited. You have to make a copy of the file to `/srv/gogs/custom/conf/app.ini` and edit that one instead.

Here are the instructions on [gogs official documentation](http://gogs.io/docs/installation/configuration_and_run.html).

**Comment by eisensheng** [comment]
The archlinux package ships with a service file for systemd. Inside this service file specifies that gogs should be started like this `/usr/share/gogs/gogs web --config /srv/gogs/conf/app.ini` so I was convinced that `/srv/gogs/conf/app.ini` is the actual config file that will be used by gogs. 

Copying the file `/srv/gogs/conf/app.ini` over to `/srv/gogs/custom/conf/app.ini` and setting `DB_TYPE = postgres` doesn't seem to have an effect at all since the gogs log show that it still initializes the sqlite3 backend: 
```
2015/07/28 22:43:23 [T] Custom path: /usr/share/gogs/custom
2015/07/28 22:43:23 [T] Log path: /var/log/gogs
2015/07/28 22:43:23 [I] Gogs: Go Git Service 0.6.1.0719 Beta
2015/07/28 22:43:23 [I] Log Mode: File(Info)
2015/07/28 22:43:23 [I] Redis Enabled
2015/07/28 22:43:23 [I] Memcache Enabled
2015/07/28 22:43:23 [I] Cache Service Enabled
2015/07/28 22:43:23 [I] Session Service Enabled
2015/07/28 22:43:23 [I] SQLite3 Enabled
2015/07/28 22:43:23 [I] Run Mode: Production
```

**Comment by manfer** [comment]
Forget about my comment. With your explanation it all indicates that `/srv/gogs/conf/app.ini` is the correct path in your case because gogs is started with that --config option.
```
2015/07/28 22:43:23 [T] Custom path: /usr/share/gogs/custom
```
Maybe you can try to put the ini in `/usr/share/gogs/custom/conf/app.ini` just to test if it works.

But @Unknwon surely knows what is going on and will tell you better.

**Comment by eisensheng** [comment]
@manfer I'm still grateful for any help in this regard. I would love to use my existing postgresql server to manage gogs data. 

Fiddling around with `/usr/share/gogs/custom` didn't helped either though. IMHO, as I interpret the Filesystem Hierarchy Standard, which Linux distributions usually follow, it would also be kind of undesired to store "Host-specific system-wide configuration files" under `/usr/share/gogs/custom`.

**Comment by wqweto** [comment]
@eisensheng The idea is to symbolic link subdirectory /custom/conf to /etc/gogs/conf or similar.

Just my $.02

**Comment by manfer** [comment]
@eisensheng three questions.

Does your PostgreSQL database has already the gogs tables? I mean where you already using that PostgreSQL database and now it doesn't work with that archlinux gogs version?

Which is your PostgreSQL version?

Has you got another PostgreSQL Server running on 127.0.0.1?

The place where you are getting the error is very curious because just before the migration the code does a connection to a database and that connection is successful as you don't receive an error for that connection.

**Comment by Unknwon** [comment]
@eisensheng 

Hi, 

> Copying the file /srv/gogs/conf/app.ini over to /srv/gogs/custom/conf/app.ini and setting DB_TYPE = postgres doesn't seem to have an effect at all since the gogs log show that it still initializes the sqlite3 backend:

It is somewhat confusion but `SQLite3 Enabled` just mean your version supports use SQLite3 as database, doesn't mean you're actually using it. Maybe I should change it to `SQLite3 supported`.

To see whether config option is working or not, you should go to URL path `/admin/config`.

Hope helps!

**Comment by eisensheng** [comment]
Thanks for responding!

> Does your PostgreSQL database has already the gogs tables?

Nope.

```
psql -h 10.0.0.10 -p 5432 -U gogs_app gogs
psql (9.4.4)
Type "help" for help.

gogs=> \d+
No relations found.
gogs=> \q
```

> I mean were you already using that PostgreSQL database and now it doesn't work with that archlinux gogs version?

Neither. I tried to install gogs from scratch and it fails to connect to the postgres Database. So I configured it to use sqlite for now but I would be happier if gogs could make good use of my postgres database. :wink:

> Which is your PostgreSQL version?
> Has you got another PostgreSQL Server running on 127.0.0.1?

I'm using PostgreSQL 9.4.4 also from the Archlinux repos. It might be useful to note that gogs runs on a Raspberry PI 2. The PostgreSQL Database happens to run on a VM and both systems are connected via a VPN setup. The VPN Setup works fine otherwise. I mean like I can connect to the PostgreSQL Server through the command line tool from the Raspberry. I checked that.

> To see whether config option is working or not, you should go to URL path /admin/config.

This is even more confusing. The HTML page shows that the `HOST` setting was read properly and has the value `10.0.0.10:5432` assigned to it. This was observed with the sqlite3 backend enabled though because gogs won't start with the postgres backend enabled after all. The command `/usr/share/gogs/gogs dump --config /srv/gogs/conf/app.ini` also fails with the same message `Fail to dump database: dial tcp 127.0.0.1:5432: connection refused` btw.

**Comment by manfer** [comment]
I would suggest to try to figure out if the problem is on xorm (it is the ORM package that gogs uses to deal with database) or on gogs.

So I would edit the file `/usr/share/gogs/models/models.go` to test.

cd into gogs directory to work from there.
```
$ cd /user/share/gogs
```
Edit the mentioned file with your favorite editor:
```
$ vim models/models.go
```
Just add a line after line 109 at the end of the `case postgres` part of the `switch` statement. Before `case "sqlite3"`:
```
log.Fatalf("CONNECTION STRING: %s ", connstr)
```
For that line of code to work you have to import the log package. So at the beginning of the file on the import statements you have to include `"log"` just where you prefer. For example:
```
import (
        "database/sql"
        "log"
        "fmt"
```
Save the file and now you have to rebuild the application. That is done by running on your terminal the command:
```
$ go build
```
Now test the dump again.
```
$ ./gogs dump --config /srv/gogs/conf/app.ini
```
That will now output the Connection String gogs is sending to xorm to connect to the database, If on that connection string the host is the one you have configured in the ini file, 10.0.0.10:5432 then almost 100% the error is in xorm code and not in gogs code.

So it would be probably useful to know which xorm version is on your system. I can be retrieved by running:
```
$ cat $GOPATH/src/github.com/go-xorm/xorm/VERSION
```
Knowing that data and if xorm is outdated, maybe it can be solved just by updated that package. Better if @Unknwon can confirm if it is safe to update the package and which is the best way to update it.

**Comment by Unknwon** [comment]
@manfer thanks your tip!

I've checked that `connstr` in Gogs is correct, which means it's problem on XORM or PostgreSQL driver.

**Comment by Unknwon** [comment]
OK, it is a bug with PostgreSQL driver, but there is a easy fix by change connection string to the new format, which has been pushed to `master`, update Gogs and rebuild should fix your problem! @eisensheng

**Comment by Unknwon** [comment]
And thanks all the help info from @manfer :+1:

**Comment by Unknwon** [comment]
Close for now, but open for continuing discussion. :dizzy:

**Comment by eisensheng** [comment]
I came back to this issue and tested it again. It's working like a charm now. Very well done and thanks for the fix!

**Comment by Unknwon** [comment]
@eisensheng thanks your confirmation!

**Comment by redmutex** [comment]
I am using gogs on production for my team and the previous it officer created everything on docker images. Now I seem to be in a big trouble with changing the connection string to suit this bug in the driver. Can you guys please help me to fix this problem?

In the server we have a docker image of gogs, another image of postgres and I am not sure how to modify the connstr here. Please help me.
