### ISSUE TITLE
Installation problem: fail to get packages 

### ISSUE THREAD

**Issue by kausters** [gogits/gogs#1403]
I am following [this guide](http://gogs.io/docs/installation/install_gogs_on_mac.html) to install Gogs on Mac OS X 10.10.4 with OS X Server. I got the impression that the guide was a bit out-of-date but most things seemed to work fine up until a point.

I'm building Gogs from source and have Go and GoPM running, but get stuck on the "gopm get -v" step when building Gogs itself. Everything is fine until two packages that fail to download:

```
$ gopm get -v
# Truncated already downloaded packages that were skipped.
[GOPM] 15-07-28 15:56:01 [ INFO] 0 package(s) downloaded, 2 failed
[GOPM] 15-07-28 15:56:01 [ERROR] golang.org/x/net: fail to get revision(golang.org/x/net): resource not found: http://code.google.com/p/go/source/browse/?repo=net&r=7dbad50ab5
[GOPM] 15-07-28 15:56:01 [ERROR] golang.org/x/text: fail to get revision(golang.org/x/text): resource not found: http://code.google.com/p/go/source/browse/?repo=text&r=5f741289c4
```

With this not complete, I cannot build Gogs to continue.
Any ideas?

**Comment by Unknwon** [comment]
Hi @kausters , I guess I put the wrong commit(from GitHub mirror) where the actual code is hosted in Google Code in .gopmfile so gopm couldn't find it.

I've pushed fixed .gopmfile to `develop` branch and you're building Gogs from `develop` branch just `git pull` update and redo `gopm get -v` should work.

Otherwise, try `go get -u github.com/gogits/gogs` and `go build` Gogs.

**Comment by kausters** [comment]
Success!
