### ISSUE TITLE
Restrict the creation of organizations

### ISSUE THREAD

**Issue by beppler** [gogits/gogs#1556]
Today any user can create an organization.

It would be useful if the creation could be restricted to users that has the administrator privilege.

The repository creation inside the organization could be made by users that are members of a team with Admin Access.

This is useful so the organization feature could be used to group repositories by departments or clients of a company.

**Comment by vijairaj** [comment]
IMHO, each deployment is different and may have conflicting requirements. For instance, my requirement is to allow **anyone** to create an organization. So, instead of hard coding these kind of policy decisions, I would suggest that a default value be provided but the ultimate decision be left to the user to decide during installation.

Please see #697 for another similar policy decision.

I guess it would be good to have a configuration option during gogs installation and have the user decide on these things. e.g. below.

Please select required deployment options
==================================
- [ ] Restrict creation of organizations.
- [ ] Enable captcha.
- [ ] More options...

**Comment by Unknwon** [comment]
@vijairaj yes, everything is/will be configurable. All in admin's hands :wink:

**Comment by bhchew** [comment]
+1 can this be in the next release?

**Comment by TheHowl** [comment]
it is planned for 0.8.0 release. So not in the immediate future, probably in a few months though. If you want to see it happen, develop it and submit a pull request!

**Comment by SourcePowered** [comment]
@Unknwon I think this should be completed as soon as possible, because it's really important.

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch, see details in https://github.com/gogits/gogs/commit/b67ec01d41ad9d504d80ffb950e161b9ce0841fc.
