### ISSUE TITLE
Run user isn't the current user: git -> gogs

### ISSUE THREAD

**Issue by Anyconcept** [gogits/gogs#1557]
Hello :)

I want to test Gogs on my server and i'm not understand why I have this error message.

I searched on Google but not answer for my..
And, I'm not an SysAdmin expert ;-)

For info, Gogs run in Debian Wheezy 
I have users "git" and "gogs"

Thanks for help :)

**Comment by Unknwon** [comment]
This error occurs when the run who runs Gogs isn't the one you configured.

**Comment by Unknwon** [comment]
Either you run Gogs as the user it requires `git` or change `RUN_USER` to `gogs`.

**Comment by Anyconcept** [comment]
... Ok, It's so good like this.
I have changed because somewhere on the doc, it says "USER_RUN =  git" :-)

Thanks for support

**Comment by Unknwon** [comment]
Well... `git` user is just a common practice ...

Has your problem been solved?

**Comment by Anyconcept** [comment]
This one, yes..
I try to solve one other :)

Thanks

**Comment by Unknwon** [comment]
No problem 😀

**Comment by stealthybox** [comment]
Thought I'd share an interesting use case and how we fixed this error:

We're using an interesting setup for our puppet control repo.
Each user auths with Kerberos authentication on the remote.
The remote has a post-recieve hook that mirrors the repo to our puppet masters:
```bash
#!/usr/bin/env bash
sudo -u puppet git push --mirror puppet_servers
```
We migrated this repo to gogs from the UI with a local migration.
We then:
- configured the `puppet_servers` remote in:
 `${GOGS_REPO_ROOT}/<org>/puppet.git/config`
- copied our post-recieve hook to:
`${GOGS_REPO_ROOT}/<org>/puppet.git/hooks/`

We use the setgid bit on the repo so that when a user auths, they operate on the remote with the permissions of the group:
`chmod -R 2775 ${GOGS_REPO_ROOT}/<org>/puppet.git`

### We also had to change the Gogs update hook:
```bash
#!/bin/bash
sudo -u puppet "/var/gogs/gogs/gogs" update $1 $2 $3 --config='/var/gogs/gogs/custom/conf/app.ini'
```
Since we're running gogs with the `puppet` user and our git user-group has password-less sudo to puppet, this allows the update-hook to run successfully without throwing the error in this issue.

This works great for us.
Hopefully it helps somebody debug something :+1:!

**Comment by YakovL** [comment]
Hello guys,

since you seem to have passed through this issue, could you please clarify it [here](https://discuss.gogs.io/t/recommended-directory-to-install-gogs-to-and-user-to-use/1764)? I didn't get what's the common practice, but since this doesn't sound as a bug, I've posted on the forum instead of GitHub, like the guidelines in the new issue form suggest.
