### ISSUE TITLE
LDAP binding fails with TLS enabled

### ISSUE THREAD

**Issue by variablenix** [gogits/gogs#1666]
LDAP binding without TLS is successful, but turning on *Enable TLS Encryption* fails with an error. I run into the same error if I also enable *Skip TLS Verify*

2015/09/21 03:49:19 [T] LDAP will use BindDN.
2015/09/21 03:49:19 [D] Using TLS for LDAP without verifying: false
2015/09/21 03:49:19 [...es/auth/ldap/ldap.go:93 SearchEntry()] [E] LDAP Connect error, example.net:LDAP Result Code 200 "": EOF

I have verified the LDAP server does support TLS by passing the *-Z* option used to "Start TLS request (-ZZ to require successful response)"

$ ldapwhoami -vvv -H ldap://ldap.example.net -x -ZZ
ldap_initialize( ldap://ldap.example.net:389/??base )
anonymous
Result: Success (0)

Gogs Version: 0.6.13.0918 Beta

**Comment by Unknwon** [comment]
Thanks your feedback!

cc @SergioBenitez can you help on this?

**Comment by SergioBenitez** [comment]
@Unknwon Sure thing.

@variablenix It seems that you are conflating "StartTLS" with "LDAP over TLS". The former refers to an insecure LDAP connection being upgraded to a secure connection over TLS, while the latter refers to a connection to an LDAP server that is initiated via TLS. The LDAP implementation in Gogs only supports the latter: LDAP over TLS, otherwise known as "secure LDAP" or "ldaps". You'll need to configure your server to support ldaps if you wish to encrypt your traffic from Gogs to the server and vice-versa.

**Comment by variablenix** [comment]
@SergioBenitez Thanks for the update. Maybe adding Start TLS v. ldaps:// can be added as a feature request so either method can be used. My understanding is LDAP over SSL or ldaps:// encryption method is deprecated. I can confirm binding over LDAPS does succeed.

**Comment by SergioBenitez** [comment]
@variablenix In my opinion, LDAPS is superior to Start TLS simply because (without too much thought, I've concluded that) Start TLS is susceptible to a downgrade attack. After some research, I've learned that this is indeed true and is termed "STRIPTLS". Further, there does not seem to be any consensus on whether Start TLS is preferred to simply using a TLS connection for LDAP specifically, and I've found no evidence that suggests that major LDAP servers will remove support for LDAPS. In fact, since LDAPS is simply LDAP over TLS, most servers require very little change to implement LDAPS, and so I see no good reason for not supporting LDAPS.

Personally, I'd recommend using LDAPS. I don't think adding Start TLS support to Gogs is a route we should take when LDAPS exists and is likely superior.

**Comment by Unknwon** [comment]
:beers:

Thank you both for discussion on this thread @SergioBenitez @variablenix :wink:

**Comment by vilppuvuorinen** [comment]
Maybe this issue should be reopened. It seems that `LDAPv2` and `ldaps` have been deprecated since 2003. In addition, the `gopkg.in/ldap.v2` library is `LDAPv3` implementation that should support `StartTLS`. Any `ldaps` compatibility is there for legacy support.

**Comment by Unknwon** [comment]
@vilppuvuorinen Thanks your info!

If `gopkg.in/ldap.v2` already supports `StartTLS`, I think the issue is solved by itself. Otherwise, nothing has changed.

So... can you offer help to test it?

**Comment by vilppuvuorinen** [comment]
I'm afraid I cannot provide any solid unit tests covering this issue. However, the `func ldapDial(ls *Source) (*ldap.Conn, error)` function could be modified to accommodate conditional/adaptive StartTLS promotion.

I could provide a pull request for this, but I don't know if the way I would implement this covers all bases. Extending models would be pretty much overkill at this point making some sort of trial and error alternative a good option. In addition, port number based optimization could make the implementation almost seamless in most setups.

When `ldapDial` is called with `UseSSL` set to `true` the port number should be checked to determine first protocol that is tried. `ldaps` uses port 636 by default making it a good first indication of the preferred protocol. Otherwise `StartTLS` is tried first. If the attempt with the preferred protocol fails the other protocol is tried instead.

Pseudo-code-ish example:

```go
if UseSSL {
  if port == 636 {
    dialTLS()
    if err {
      dialStartTLS()
    }
  } else {
    dialStartTLS()
    if err {
      dialTLS()
    }
  }
}
```

Pros:

* Zero configuration
* No api/documentation changes
* First try is successful in most setups

Cons:

* Worst case is that both protocols are tried on every authetication

What do you think? Should I go ahead with a PR?

**Comment by vilppuvuorinen** [comment]
On the other hand. Openshift does have pretty compelling implementation for `ldaps` and `StartTLS` selection: https://github.com/openshift/origin/blob/89d213ab9a04acaaa8def766c5f3e5c8ebd953be/pkg/auth/ldaputil/client.go#L79

**Comment by Unknwon** [comment]
Looks like one comment is missing?

**Comment by vilppuvuorinen** [comment]
Yeah. I ended up deleting for some reason. Sorry about that. 

However, the approach from Openshift should work, but it will break insecure ldap auth on some of currently running instances where insedure tls is not explicitly set. Running a migration toggling insecure TLS on when use tls is not checked could prevent this.

**Comment by Unknwon** [comment]
> However, the approach from Openshift should wor

I'm confused somehow, shouldn't the work already be done by the ldap.v2 package?

**Comment by vilppuvuorinen** [comment]
The support is there, but StartTLS elevates the connection from regular one.

`ldaps`

```go
con, err = ldap.DialTLS("tcp", l.host, tlsConfig)
```

`ldap` over TLS'

```go
con, err = ldap.Dial("tcp", l.host)
err = con.StartTLS(tlsConfig)
```

In Openshift the insecure TLS flag is used to select correct protocol:

```go
switch l.scheme {
	case SchemeLDAP:
		con, err := ldap.Dial("tcp", l.host)
		if err != nil {
			return nil, err
		}

		// If an insecure connection is desired, we're done
		if l.insecure {
			return con, nil
		}

		// Attempt to upgrade to TLS
		if err := con.StartTLS(tlsConfig); err != nil {
			// We're returning an error on a successfully opened connection
			// We are responsible for closing the open connection
			con.Close()
			return nil, err
		}

		return con, nil

	case SchemeLDAPS:
		return ldap.DialTLS("tcp", l.host, tlsConfig)

	default:
		return nil, fmt.Errorf("unsupported scheme %q", l.scheme)
	}
```

_Enable TLS Encryption_ could be used instead of the `scheme` field and _Skip TLS Verify_ instead of `insecure`field. Current configuration parameters are sufficient, but the labels are a bit off.

**Comment by Unknwon** [comment]
Thanks @vilppuvuorinen !

Maybe it's a good chance to propose a PR?

**Comment by vilppuvuorinen** [comment]
That's what I was thinking. I'll try to cook up one.
