### ISSUE TITLE
You can clone any user's repo in the local gogs instance.

### ISSUE THREAD

**Issue by TheHowl** [gogits/gogs#1733]
Take a look at the screencast: http://y.zxq.co/iujgsd.mp4

Using the local path function, you can clone a repo from another user in the same gogs instance. With a few retries, you can clone any user's private repositories from the same gogs instance. you just need to find out the folder where repos are stored.

**Comment by tboerger** [comment]
More or less some kind of expected behavior... But it would make sense to reject the realpath of the gogs repos if it's a local path.

**Comment by FSMaxB** [comment]
If this works even if the original repository is private, this isn't expected behavior but a high profile security flaw.

**Comment by tboerger** [comment]
A bare repo got no private or public checks. So this is expected behavior. Gogs requires just some validation.

**Comment by FSMaxB** [comment]
It looks to me like this repository was created using gogs via the Web UI. If you can simply clone everything from inside gogs' home directory, every private repository suddenly becomes accessible (readonly) by every user of this gogs instance. I really doubt that this is intentional.

In my opinion, letting a user clone repositories from the local file system is a bad idea in the first place.

But even if cloning from the local filesystem has to be supported, acess to gogs' home directory or at least the directory containing the repositories should be denied, because, as I said, it defeats parts of the purpose of private repositories.

**Comment by tboerger** [comment]
And now read my comments again. I already said that there should be a validation that prevents migrations from the gogs repo directory.

**Comment by FSMaxB** [comment]
Yeah, right, you said that. Sorry for wrongly interpreting the words you said, it wasn't clear to me that you meant the same thing.

**Comment by TheHowl** [comment]
IMHO there should be an option to still allow bare repo cloning from the file system, because it still makes sense if you're using gogs internally in a company and need to migrate repos from an old git service. However if the gogs instance is public, this is a HUGE security flaw, and thus cloning from local filesystem of server should be strictly forbidden.

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is basically duplicated to https://github.com/gogits/gogs/issues/1511
