### ISSUE TITLE
Ability to fork own repository to accessible organizations

### ISSUE THREAD

**Issue by kylewolfe** [gogits/gogs#1791]
The fork button does not work if clicking a project that is owned by the logged in user. It should be allowed so that the a user can fork their own repository in to a group that they have access to.

The opposite scenario does currently work, though (forking from a group into the users namespace).

**Comment by Unknwon** [comment]
You're right, thanks your feedback!

**Comment by fobyy** [comment]
In my case, the forking issue is really a problem. Indeed, a user cannot fork several time the same repository.

My case of use:
->A Git repo contain a dataset
->Users fork this repo to make script about this dataset
->When clicking on the fork button in dataset repo, users can see all script from this dataset.

Maybe i am in a wrong way i have to look an other solution...(use submodule?)

**Comment by Unknwon** [comment]
In a second thought, I don't think fork own repo is useful after all. Just create another branch then send pull request.

**Comment by bkcsoft** [comment]
@Unknwon forking ones own repo is definitively useful in some cases :/

I for example have a base-repo for API-based web-services that I fork when
I start a new project.

**Comment by Unknwon** [comment]
@bkcsoft sounds like a seed project, but I think just migrate the seed repository fits better in this case. Migration is not only for external repos.

**Comment by bkcsoft** [comment]
@Unknwon definitively a seed project, but I keep them as forks, so I can
make PRs from the seed when I fix something that should be in all projects
:smilie:

**Comment by Unknwon** [comment]
Sounds like a hack... Let's focus on relative more values work first..

**Comment by JokerQyou** [comment]
Create an organization and put the seed repo there, and anyone with read permission will be able to fork it.

**Comment by bkcsoft** [comment]
@JokerQyou Still can't fork it multiple times :unamused:

**Comment by kylewolfe** [comment]
This "feature" is available on both github and gitlab. It is often a needed on to enable certain workflows, including my use case.

**Comment by Unknwon** [comment]
I can't seem to fork my repo on GitHub.

**Comment by kylewolfe** [comment]
Which repo are you referring? I just tested on several repos under my name and I have the option to fork to groups that I have write access to.

**Comment by Unknwon** [comment]
>I have the option to fork to groups that I have write access to.

Oh.. OK, still not possible to fork under my personal account domain..

**Comment by kylewolfe** [comment]
Can you expand on "fork under personal account domain"? The goal is to fork from your namespace (eg /kylewolfe/foo) to a project you have write access to (eg /someGroupIHaveWriteAccessTo/foo).

This works for me on GitHub, GitLab, but not Gogs. Gogs does however support the opposite (group/foo to kylewolfe/foo).

**Comment by JokerQyou** [comment]
Okay, so we all misunderstood what you said... I thought you want to fork your own project to your personal account.

**Comment by 0x6C77** [comment]
I have the same issue as @bkcsoft where I use a repository as a boilerplate for all my projects. If forking the boilerplate is "hacky" what would be the correct way to do it?

**Comment by bard** [comment]
Consider this scenario:

1. Bob works at Acme, Inc. and is the main developer of an API gateway
2. Acme also works on services A, B and C, each represented in Gogs as an organization
3. All services/organizations use Bob's API gateway
4. At least for now, Bob is the only developer in service/organization B

I think the best approach is for Bob to own the API gateway repo and for each organization to fork it. That way organizations can make local changes to the gateway and then upstream them through carefully reviewed pull requests. The alternative—to give every organization access to the API gateway repo and manage a branch—branch, doesn't sound right.

The problem comes with point 4): at the moment Bob can't fork his own repository, even if it would end up being conceptually owned by organization/service B.

This is a contrived example for clarity's sake. In reality I'm bumping into this through the much more common case of working on two projects (modelled as organizations), both relying on another project of mine. To manage this through branches would be less work but still conceptually wrong, IMHO.

So can we please allow forking own projects into an organization's space?

**Comment by lunny** [comment]
Gitea has merged. See this PR https://github.com/go-gitea/gitea/pull/761

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
