### ISSUE TITLE
git relative submodule link

### ISSUE THREAD

**Issue by rabits** [gogits/gogs#1926]
When I use .gitmodules with relative url:
```ini
[submodule "exmod"]
	path = exmod
	url = ../exmod.git
	branch = master
```
Gogs makes wrong url to target repo:
* When I'm in the parent repo on "https://git.example.com/exuser/exproj" - link to the exmod submodule is "https://git.example.com/exmod"
* When I'm in the parent repo on "https://git.example.com/exuser/exproj/src/master" - link to the exmod submodule is "https://git.example.com/exuser/exmod"

These links should point to "https://git.example.com/exuser/exmod" in both cases.

**Gogs version**: release 0.7 (0.7.0.1107 Beta)
**Git version**: 1.9.1
**System**: Ubuntu 14.04 64

**Comment by Unknwon** [comment]
Thanks your feedback!

Is `.gitmodules` a file in the root directory of repository?

**Comment by rabits** [comment]
Yeah, it is just a git submodule control file

**Comment by Unknwon** [comment]
OK, thanks!

**Comment by goriy** [comment]
I've got (maybe) similar issue.
There are two repositories:

`https://example.com/myuser/repo1`
and
`https://example.com/myuser/repo2`

At root of repo1 there's `.gitmodules` file:

    [submodule "shared/repo2"]
        path = shared/repo2
        url = ../repo2
        branch = master

When I do `git clone  --resursive` on client it works right for both `https` and `ssh` urls.

When I look at repo1 in browser in `shared` directory (`https://example.com/myuser/repo1/src/master/shared`) I see wrong link to repo2 as submodule. It points to `https://example.com/myuser/repo1/src/repo2`.

It seems that correct link address should be `https://example.com/myuser/repo2` or `https://example.com/myuser/repo2/src/master`. 

Relative submodule url base is parent repository's root (according to git submodule documentation) - not submodule "mount point".

Gogs version: 0.9.13.0318
Git version 2.1.4
System: Debian 8.4

**Comment by amery** [comment]
relative url submodules in gogs have only two valid representations. `../foo` becoming `/same-orga/foo` and `../../foo/bar` becoming `/foo/bar`. any other flavour (`./` or more than two `../` blocks) doesn't have place on a gogs server and shouldn't be represented as links at all.

I've tried to make sense of the related code in http://github.com/gogits/git-module but I'm still not sure how to fix this problem. any suggestion?

**Comment by goriy** [comment]
Disclaimer: I have no knowledge neither about Go language nor about project internals. I've even never seen any Go code before, but it hadn't stopped me ))

I've installed gogs from source and have tried some quick-and-dirty blind hacking-debuging.

As I can see in the file https://github.com/gogits/git-module/blob/master/submodule.go you mentioned - in function _RefUrl_ (line 32) there's no special case about relative urls. In my naive novice opinion It can be added near line 52 as 
 
```
// neither '@' nor ':' was found in url variable
if i < 0 && j < 0 {
  ...construct and return correct submodule url here... 
}

```
Alternatively it can be done by means of condition:

```
// relative url prefix check (according to git submodule documentation)
if strings.HasPrefix(url, "./") || strings.HasPrefix(url, "../") { 
  ...construct and return correct submodule url here... 
}
```

One problem remains - I can't see parent repo url in this function to create new url (remember - I've got no knowledge about this project's internals, maybe it's really possible to get one there).
But it can be added as a second parameter to this function (maybe it's a very dirty hack and things should be done in very different manner, I don't know). I've done "grep" at code and noticed that function _RefUrl_ is called in https://github.com/gogits/gogs/blob/master/templates/repo/view_list.tmpl (lines 33 and 34), so parameter value should be set there.

Looking around this template (I know nothing about project internals, so globals, structures, variables used are "in the dark" for me yet) I've tried some hopeful ones.

It seems that $.BranchLink contains desired information and fits to be used as second parameter to _RefUrl_ function. So, urlPrefix parameter, url variable and second parameter in function _RefUrl_ ($.BranchLink from template) can theoretically be enough to construct correct submodule url and return it from function.

Maybe all I said above is an utter crap and things should be fixed in completely different way. Lack of knowledge makes it impossible for me to see "the whole picture" yet.

**Comment by goriy** [comment]
> any other flavour (./ or more than two ../ blocks) doesn't have place on a gogs server and shouldn't be represented as links at all.

There's possibility that it will be changed in future (there are even feature-requests about it - #1061, for example), so I don't think that it's a good idea to restrict number of processed "../" blocks

**Comment by amery** [comment]
It was only to simplify the request.

**Comment by goriy** [comment]
OK. Sorry for my misunderstanding.

**Comment by Unknwon** [comment]
This is claimed to be fixed by merging https://github.com/gogits/git-module/pull/14, please help test on `develop` branch or https://try.gogs.io.

Be sure to update dependency `github.com/gogits/git-module`.

**Comment by goriy** [comment]
I've checked my example at https://try.gogs.io/illustr/repo1. It seems to work fine

**Comment by Unknwon** [comment]
Close as fixed.
