### ISSUE TITLE
Ability to map extensions for syntax highlighting in config

### ISSUE THREAD

**Issue by coredumb** [gogits/gogs#2103]
It would be nice to be able to map extensions to a specific language for syntax highlighting

**Comment by yurivict** [comment]
Extensions alone isn't good enough. Like the example in #2206.

file(1) is able to tell the type of these files correctly even when extension is wrong.

**Comment by Unknwon** [comment]
`file(1)` one?

**Comment by yurivict** [comment]
Here is the file utility: ftp://ftp.astron.com/pub/file/
It has libmagic included in it.
It does much better than just extensions.

**Comment by Unknwon** [comment]
Thanks your link... but I don't get it what does it mean?

**Comment by yurivict** [comment]
GitHub highlights https://github.com/yurivict/vm-to-tor/blob/master/rc.conf.simple.sample correctly, and gogs doesn't.

Obviously GitHub have some method of telling the file type better than just by extension.

ftp://ftp.astron.com/pub/file/ contains the 'file' utility. It is able to almost always tell the type of file, regardless of extension.

This 'file' utility uses the library 'libmagic' that is included there too.

Maybe you should use this method instead of using extensions?

**Comment by Unknwon** [comment]
OK... kind of knowing what it is.

But no, Gogs would continue use highlightjs and see what we can do with it.

**Comment by yurivict** [comment]
highlightjs is okay, they fail to determine the file type though.

**Comment by Unknwon** [comment]
No... actually I already know where can be improved, but details are not useful to ends users.

**Comment by yurivict** [comment]
Please note that .pro and .qrc files don't get highlighted, like here https://github.com/tux3/qTox/blob/master/qtox.pro

**Comment by Unknwon** [comment]
It is now possible on `develop`.

Example:

```ini
[highlight.mapping]
.toml=ini
```

**Comment by Unknwon** [comment]
Close as implemented.
