### ISSUE TITLE
Syntax highlighting is done on plain text LICENSE files

### ISSUE THREAD

**Issue by yurivict** [gogits/gogs#2181]
For example, this file when migrated into Gogs is highlighted:

https://github.com/yurivict/node-line-tracer/blob/master/LICENSE

**Comment by linquize** [comment]
gogs mis-treat it as something like shell script?

**Comment by yurivict** [comment]
yes

**Comment by Unknwon** [comment]
Fixed in `develop` branch. See in action: https://try.gogs.io/gogs/gogs/src/develop/LICENSE

**Comment by megadr01d** [comment]
Any special reason to fix incorrect highlighting only on `LICENSE` files? This can't be right.
All files using the standard `.txt` extension or files without an extension (usually in all caps, but not necessarily) like `README, CHANGELOG, LICENSE, HISTORY, meta, todo` etc., should not be highlighted because they're readable plain text.

Some examples below.

[LICENSE](https://git.teknik.io/dmz76/test/src/master/LICENSE) - Not an actual LICENSE file, just renamed that way so no highlighting occurs
[LICENSE2](https://git.teknik.io/dmz76/test/src/master/LICENSE2) - A number added to `LICENSE` automatically highlights the text
[LICENSE.txt](https://git.teknik.io/dmz76/test/src/master/LICENSE.txt) - the standard `txt` extension automatically highlights the text

**Comment by megadr01d** [comment]
@Unknwon Should I create a new issue?

**Comment by Unknwon** [comment]
@megadr01d 

>Any special reason to fix incorrect highlighting only on LICENSE files? 

https://github.com/gogits/gogs/blob/master/modules/template/highlight/highlight.go#L16

**Comment by megadr01d** [comment]
@Unknwon I see. But what about any file with a `.txt` extension getting highlighted? [`highlightExts`](https://github.com/gogits/gogs/blob/master/modules/template/highlight/highlight.go#L28) is not including `.txt`.

Does `.txt` have to be explicitly added in [`highlightMapping`](https://github.com/gogits/gogs/blob/master/modules/template/highlight/highlight.go#L64)?

**Comment by Unknwon** [comment]
@megadr01d there is no perfect solution for highlighting, but I think in your case add following content to your `app.ini` should disable highlighting for `.txt` files:

```
[highlight.mapping]
.txt= nohighlight
```

**Comment by megadr01d** [comment]
@Unknwon Since I'm using a 3rd party hosted Gogs, let me get back to you, on this, before I close this and the other issue I created. I thought it was a bug within Gogs but I see it's normal behavior of highlightjs.
