### ISSUE TITLE
rename organization redirect to old name cause 404 error

### ISSUE THREAD

**Issue by niphor** [gogits/gogs#2268]
Location in 302 Header does not use the new name

**Comment by Unknwon** [comment]
This issue is claimed to be fixed by merging #2270

**Comment by Sauermann** [comment]
A similar things happens in v0.8.10.1217 when a repository is renamed.
After renaming
gogs.example.com/Orgamization/OldName
to
gogs.example.com/Organization/NewName
one is redirected to the page
gogs.example.com/Orgamization/OldName/settings
which does not exist (404)

**Comment by Unknwon** [comment]
Please read comments before commenting.

**Comment by Sauermann** [comment]
I did read the comments.
Just wanted to point out that there is a similar issue with renaming repositories.
Since #2270 does not fix the problem for repositories renaming, I made the comment.
Should I create a separate issue for the repository renaming problem instead?

To be sure, I just verified that my mentioned issue is not resolved on try.gogs.io v0.8.13.1227.

**Comment by Unknwon** [comment]
I see, thank for clarifying!

**Comment by Unknwon** [comment]
@Sauermann please checkout `develop` branch or https://try.gogs.io/ again!

**Comment by Sauermann** [comment]
In try.gogs.io v0.8.14.1230 renaming repositories works without a 404.
Also checked Organization renaming and I did not get a 404.

**Comment by Unknwon** [comment]
Great!
