### ISSUE TITLE
Truncate repository name if too long

### ISSUE THREAD

**Issue by drsect0r** [gogits/gogs#2287]
If the name of the repository is too long It would be nice to truncate it with dots instead of messing up the dashboard.

**Comment by Unknwon** [comment]
Thanks your feedback!

Any screenshots?

**Comment by drsect0r** [comment]
Right now I can't, however, a name longer than 40 characters should do it.

Happy Christmas!

**Comment by Unknwon** [comment]
ping @drsect0r

**Comment by drsect0r** [comment]
![screenshot from 2016-01-02 02-09-31](https://cloud.githubusercontent.com/assets/9106228/12072812/e2683f1a-b0f5-11e5-9491-36e8cfd9334e.png)

**Comment by Unknwon** [comment]
Thank you!

**Comment by stonewareslord** [comment]
From my duplicate issue:

Here's a screenshot of the sidebar and news feed:

https://cloud.githubusercontent.com/assets/7482347/12149353/52e243b6-b471-11e5-919c-4c55b8d912b3.png

The names stretch past the "My Repositories" box and push the stars down. The second repo's star shifts `repo-2`'s star to the left. In the news feed, the name overlaps with the repo icon. Github has some examples of of how this could be fixed

by using ellipses:

https://cloud.githubusercontent.com/assets/7482347/12149579/58dae5b0-b472-11e5-81b7-d99d570dca4a.png

by breaking the line:

https://cloud.githubusercontent.com/assets/7482347/12149547/38a5b450-b472-11e5-8614-507804033e34.png

Both repositories have names with the maximum length (100)

**Comment by Unknwon** [comment]
Thanks your info @stonewareslord !

**Comment by Unknwon** [comment]
Hi all, please test out `develop` branch or https://try.gogs.io/

**Comment by stonewareslord** [comment]
It almost works well. The repo names are truncated correctly on the dashboard:

![selection_001](https://cloud.githubusercontent.com/assets/7482347/12341345/f4851bd4-baee-11e5-97bb-9194828f4b3d.png)

The repo URL on the right (in `My Repositories`) works, but the URL in the news feed doesn't. It is linking to `try.gogs.io/username/repon...` instead of `try.gogs.io/username/reponame` which gives a 404. 

One more issue is that in the project page, the project name pushes down the `Unwatch` or `Star` buttons:

![selection_002](https://cloud.githubusercontent.com/assets/7482347/12341398/542d3562-baef-11e5-8f3d-a636950e42e2.png)

![selection_003](https://cloud.githubusercontent.com/assets/7482347/12341401/5a47007c-baef-11e5-8bcd-cc4e987a21d9.png)

The profile page works well if the monitor is large enough:

![selection_004](https://cloud.githubusercontent.com/assets/7482347/12341410/79ce4e46-baef-11e5-9d2a-6db3cca68d20.png)

But when the window is smaller than the repo name, it just cuts off (instead of being broken into two lines as in the last Github screenshot in my previous comment):

![selection_005](https://cloud.githubusercontent.com/assets/7482347/12341437/aaa6f72a-baef-11e5-8311-46ee3e7d10a8.png)

Here is what the dashboard and repo pages look like on a smaller monitor:

![selection_006](https://cloud.githubusercontent.com/assets/7482347/12341471/f7715186-baef-11e5-87e5-646779cdbee1.png)

![selection_007](https://cloud.githubusercontent.com/assets/7482347/12341472/f8e8c918-baef-11e5-9663-848da9001d53.png)

They look okay to me with the exception of the repo name pushing `Unwatch` and `Star` down.

**Comment by Unknwon** [comment]
@stonewareslord URL fixes are pushed to `develop`.

And I found `word-break: break-all` does not work on Firefox, but perfectly under Chrome. I suggest you open another issue for this problem specifically since the main purpose of this issue is completed.

**Comment by bygreencn** [comment]
are you tried the full function test, this fix may cause the error message about  "template: user/dashboard/feeds:10:52: executing "user/dashboard/feeds" at <.ShortActUserName>: ShortActUserName is not a field of struct type *models.Action".

**Comment by Unknwon** [comment]
@bygreencn I think you update the source code but did not recompile the Gogs..?

**Comment by bygreencn** [comment]
i use there commands as:
go clean -a 
go clean -a -tags "tidb sqlite cert"
go build -a -tags "tidb sqlite cert"
but it is the same, anything wrong?

**Comment by Unknwon** [comment]
@bygreencn I see, I think you're talking about this: https://github.com/gogits/gogs/issues/2416

**Comment by Unknwon** [comment]
Close as fixed.
