### ISSUE TITLE
maybe the apt-get package can install all dependencies

### ISSUE THREAD

**Issue by mgracer48** [gogits/gogs#2313]
that be nice
it can ask for the stuff u want like mysql instead or postgresql (you choose basically)

**Comment by mgracer48** [comment]
it will also ask you neccessary stuff like the url for where it should be hosted

**Comment by Unknwon** [comment]
Just a note that this is not managed by Gogs, but hhttps://packager.io/ .

cc @crohr

**Comment by xor-gate** [comment]
I think gogs should have *real* debian package building instead of https://packager.io as I tried it myself on a simple http server package and installed 23 MByte of crap and weird init scripts on my system and was not conforming to the the Debian Maintainers Guide (https://www.debian.org/doc/manuals/maint-guide/). Then the debian package could have recommended depencies.

**Comment by Unknwon** [comment]
@xor-gate that's cool. But no one here knows how to do `real debian package building` and let someone contribute seems will end up same situation as right now.

**Comment by Unknwon** [comment]
@crohr sorry for bothering you over and over.. do you have comments on this?

**Comment by Unknwon** [comment]
Any updates?

**Comment by Unknwon** [comment]
Close for now but open for continuing discussion.
