### ISSUE TITLE
Nicknames are lower-cased in Dashboard panel

### ISSUE THREAD

**Issue by xDShot** [gogits/gogs#2375]
Users' nicknames contain both UPPER and lower case letters, but in Dashboard they all sometimes appear lower-cased. Here is screenshot:
![_2016-01-10_13-22-25](https://cloud.githubusercontent.com/assets/4261659/12221087/7565f16a-b79d-11e5-9c67-04db4f573a86.png)

**Comment by exmex** [comment]
![](http://i.imgur.com/pAxhgPB.png)

Same here.

**Comment by sapk** [comment]
Find this : https://github.com/gogits/gogs/blob/4993ab1a767bea5645a65b5639cc00bb107fdfd3/models/issue.go#L1598 

L1603 and L1604 same problem

**Comment by sapk** [comment]
@exmex What is the diff between the two push ? You use http for one and ssh for the other ?

**Comment by exmex** [comment]
These are different repositories. I use http pushing only.

**Comment by sapk** [comment]
Don't know if this line should also be edited for consistency : https://github.com/gogits/gogs/blob/19423957b17fe583e9a04f45aafe91335354d6e2/models/action.go#L539 
cc @Unknwon

**Comment by sapk** [comment]
I think for the push it come from here https://github.com/gogits/gogs/blob/4993ab1a767bea5645a65b5639cc00bb107fdfd3/routers/repo/http.go#L137 and that it should be outside of the error handling. 
But since it touch to the auth, I don't want to mess it all. 
A simpler solution could be to edit this line https://github.com/gogits/gogs/blob/4993ab1a767bea5645a65b5639cc00bb107fdfd3/routers/repo/http.go#L205 and replace authUsername with authUser.Name

**Comment by Unknwon** [comment]
Thanks @sapk !

> Find this for the comment part : https://github.com/gogits/gogs/blob/4993ab1a767bea5645a65b5639cc00bb107fdfd3/models/issue.go#L1598

>L1603 and L1604 same problem

I agree this is the problem.

**Comment by redoz** [comment]
It also converts the repository names to lower case, it would be nice if the original casing was preserved there too.

**Comment by Unknwon** [comment]
This problem should no longer exists, please re-test with latest `master`.
