### ISSUE TITLE
Synchronize issues with Github 

### ISSUE THREAD

**Issue by nioc** [gogits/gogs#2471]
Is there a way to synchronize issues with Github?
I write a little php script that reads gogs database and calls [Github issue API](https://developer.github.com/v3/issues) to create it. I think this feature should be a part of the issue creation in gogs.
Another way, user should querying Github issues and create/update its in Gogs

**Comment by bkcsoft** [comment]
No there's no way to synchronize issue with Github at the moment. Only way to do it is manually like you're doing now.

For the Feature-Request part, I'd argue that it'd be more useful to implement webhooks for issues, since otherwise Gogs would have to implement a new 'issue-provider' everytime someone wants to use YetAnotherIssueTracker (I'm fairly certain that that exists btw :laughing:). And you'd be able to use you're current php-script with very little changes :wink:

Personally, I use BitBuckets integrated issue-tracker, Trello (not really a 1:1-sync...), Github issues and Asana. So already we're at 4 different providers and I could keep listing more :unamused: 
Having issue-tracking exposed on a webhook would also allow for Slack-integration and similar services without having to write YetAnotherServiceIntegration.

All-in-All, Webhooks rules, and hardcoded integrations sucks :stuck_out_tongue_winking_eye:

**Comment by nioc** [comment]
If we can have bidirectional synchronization through webhook, i'll sign this deal :smile
@bkcsoft do you have any tutorial on how to set up issues webhook?
If i my understanding is correct, system A (github ie) triggers the webhook on event (issue creation /modification ie) and calls an url in system b (gogs ie). And what next? There is a way to create gogs issue at this call receiving?

**Comment by Unknwon** [comment]
Thanks your feedback!

What is the use case of sync issues from GitHub?

**Comment by nioc** [comment]
I want to use github as a public repo where users should create issues, synchronize these issues on gogs (which is used as our private repo with dev comments on issues).

**Comment by bkcsoft** [comment]
@nioc bi-directional would require you to setup webhooks both ways, so github fires a webhook to update gogs, and gogs would fire a webhook to update github. Github has this feature, so you can today do unidirectional syncing from github to gogs (e.g. for using gogs as a backup-site), but Gogs doesn't have this type of webhook (only push-events and branch/tag-events are handled) so you can't do it bi-directional or have Gogs serve as a master...

@Unknwon Mainly for backups or for having a dummy-repo with issue-tracker on Github and have everything code-related on Gogs, but still be able to handle issues from within Gogs

**Comment by bkcsoft** [comment]
If Gogs where to get on par with Github webhook-wise, one could write third-party services to synchronize everything between github and gogs, for redundancy if one of the sites goes down (network-issues, harddrive-failures, etc) (Generally a good idea :wink: )

**Comment by nioc** [comment]
@bkcsoft understood. If you can explain me what to set in the github webhook for create / update issues on gogs side, I'll be grateful :smiley:

**Comment by bkcsoft** [comment]
In the repo-page goto `Settings=>WebHooks=>Add Webhook` then check `Let me select individual events.` and check `Issues` (nothing else). set the URL to wherever you have your php-script running (preferably have it check the secret...) and see these two links for payload-description for Issues
https://developer.github.com/v3/activity/events/types/#issuecommentevent
https://developer.github.com/v3/activity/events/types/#issuesevent

**Comment by bkcsoft** [comment]
Unless someone actually wants an out-of-the-box integration with github (generally not what you want), this would be a duplicate of #2319 :smiley:

**Comment by nioc** [comment]
Thanks for the links. If i write such a script, i'll post it as a gist for sharing.
Agreed with the duplicate, i'll close mine.

**Comment by Unknwon** [comment]
Wouldn't two-way sync of issues be a mess ... :sweat:
