### ISSUE TITLE
Add crond to the dockerfile

### ISSUE THREAD

**Issue by Kyosfonica** [gogits/gogs#2597]
Currently the docker container contains crond (the cron daemon) installed but it is not started automatically at start.
Could you guys fix this?

Thanks

**Comment by Unknwon** [comment]
cc @0rax

**Comment by 0rax** [comment]
Hi there, I will add this feature later today and will reference this issue in my PR when ready.

Thanks for your report.

**Comment by Kyosfonica** [comment]
Thanks this will help me a lot :)

**Comment by 0rax** [comment]
The PR is made see :arrow_up:, I've made this feature opt-in (using the `RUN_CROND` environment variable) as I dont think everybody will require this feature.

I just have a quick question, why do you need the cron daemon to be running inside your docker container as gogs is handling its cron jobs using its own scheduler ?

PS: Sorry for the commit spam, I had to make a change and forgot to add it before rebasing ...

**Comment by Kyosfonica** [comment]
Because gogs do not perform autobackups, so I made my own script to handle them but need cron to launch it at the given time.

**Comment by Unknwon** [comment]
This is claimed to be implemented by merging https://github.com/gogits/gogs/pull/2605

**Comment by 0rax** [comment]
@Kyosfonica I see, my guess would be the easiest (and cleanest) way to implement that would be to mount the data volume in another container running only crond (so that you dont rely on the same container to backup & proide your data).

But as gogs already uses a process manager to run everything needed, it does not really add a layer of complexity to the container so why not :) I was just wondering why this was needed inside the gogs container.

**Comment by Unknwon** [comment]
Actually I'm wondering the same thing...

**Comment by vision-ken** [comment]
another container dosn't has `gogs backup` command.
