### ISSUE TITLE
LDAP Search failed unexpectedly

### ISSUE THREAD

**Issue by kop** [gogits/gogs#2628]
Hi,

I'm trying to configure Gogs to use LDAP service from [JumpCloud](https://jumpcloud.com/) and having the following error during the auth:

```
2016/02/15 18:19:18 LDAP will use BindDN.
2016/02/15 18:19:18 Search for LDAP user: <username>
2016/02/15 18:19:18 Bound as BindDN uid=<bind username>,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
2016/02/15 18:19:18 Searching using filter (&(objectClass=inetOrgPerson)(uid=<username>))
2016/02/15 18:19:18 Binding with userDN: uid=<username>,ou=Users,o=55fcb6467ff1ab131d018642,dc=jumpcloud,dc=com
2016/02/15 18:19:18 Bound successfully with userDN: uid=<username>,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
2016/02/15 18:19:18 ...gogs/models/login.go:246 LoginUserLDAPSource()] [E] LDAP Search failed unexpectedly! (0 entries)
```

Can't really understand what does this mean.

And here is the config I'm using:

![gogs-auth](https://cloud.githubusercontent.com/assets/645148/13059605/058522ea-d434-11e5-96df-3e4710efb219.png)

**Comment by Unknwon** [comment]
Hi, I think it means nothing return/found by the information you provide.

**Comment by Unknwon** [comment]
cc @SergioBenitez @nanoant

**Comment by kop** [comment]
@Unknwon, I thought about this too, however it looks strange because it says that it's binded to userDN. No user data found (like first name, last name, etc)? But it should be there and I'm using all field names provided by JumpCloud support.

**Comment by Unknwon** [comment]
I think you would have to take a screenshot of your config first..

**Comment by kop** [comment]
Sure, config is added.

**Comment by Unknwon** [comment]
Thanks! I don't know LDAP very well, we'll wait who knows better come to help. :sweat:

**Comment by nanoant** [comment]
@Unknwon this is something else, because user lookup using BindDN succeeds, but then we Gogs tries to bind the user and using his/her password then it queries again for the user attributes in `modules/auth/ldap/ldap.go:154`. For some reason this query does not return anything.

@kop It looks like your server does not return anything on user asking for his/her own attributes, which is weird. Thoughts!?

**Comment by Unknwon** [comment]
@nanoant ah, good to learn!

**Comment by nanoant** [comment]
@Unknwon just wondering maybe we should do the attributes lookup in BindDN context, not in user context, as user may not have rights to do any search in LDAP, even if the result will be him/herself, which is probably the case of JumpCloud?

I think the implementation for BindDN mode arrived in 7d84d4a8 done by @SergioBenitez. Just curious why @SergioBenitez made the attribute search in the UserDN context not in BindDN.

**Comment by kop** [comment]
@nanoant I think you are right with UserDN context. In JumpCloud there are a special switch that allows a user to perform a search in LDAP.

My BindDN user has this enabled while user I'm trying logging with don't have such permissions.

**Comment by nanoant** [comment]
@kop @Unknwon Okay I'll submit a PR so when using BindDN the attribute fetch is done in user context but not using the LDAP filter, which may need extra permissions for regular users, so instead just querying user own attributes.

@kop in meantime you may check if you can successfully execute this, ensuring user is able to lookup its own attributes (which is IMHO minimum requirement)
~~~
ldapsearch -H ldaps://YOURLDAPSERVER -b uid=<username>,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
-W -D uid=<username>,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com did givenName sn mail
~~~

**Comment by Unknwon** [comment]
> @kop @Unknwon Okay I'll submit a PR so when using BindDN the attribute fetch is done in user context but not using the LDAP filter, which may need extra permissions for regular users, so instead just querying user own attributes.

How would this affect existing users who want to query under  in user context?

**Comment by nanoant** [comment]
> How would this affect existing users who want to query under in user context?

First of all you don't need LDAP filter to do query. It is optional, but Gogs makes it required, but it makes completely no sense to use it, because if the user is logged then it does not need to filter (lookup) himself, because he/she is the search base, so we need just to grab own attributes.

**Comment by Unknwon** [comment]
OK... just wonder why no one else reports this that I know some people is using the admin filter? Does that somehow make any differences?

**Comment by nanoant** [comment]
Because some LDAP servers are so smart/or dumb and let you use filter when it is gonna to match yourself. Still I need to make sure @kop can run this filter-less query successfully, because if not then there's something wrong with JumpCloud config.

Btw. shouldn't LDAP module be external, rather than merged with Gogs source? Is it a fork of https://github.com/mmitton/ldap? Because if you move out Git module to external dep, shouldn't we do the same for LDAP?

**Comment by Unknwon** [comment]
> Btw. shouldn't LDAP module be external, rather than merged with Gogs source? Is it a fork of https://github.com/mmitton/ldap? Because if you move out Git module to external dep, shouldn't we do the same for LDAP?

No, the core lib is 3rd party, `modules/auth/ldap` is just a wrapper specifically for Gogs.

**Comment by nanoant** [comment]
> No, the core lib is 3rd party, modules/auth/ldap is just a wrapper specifically for Gogs.

Ahh... I am blind as usual, I've overlooked that you've switched to `gopkg.in/ldap.v2` in aaa3f1b2b9de437386185670bcc135202f1d8099 :)

**Comment by Unknwon** [comment]
:sweat_smile:

**Comment by kop** [comment]
@nanoant, just tested the given query. Everything works:

```
# extended LDIF
#
# LDAPv3
# base <uid=ivan.koptiev,ou=Users,o=organizationID,dc=jumpcloud,dc=com> with scope subtree
# filter: (objectclass=*)
# requesting: did givenName sn mail 
#

# ivan.koptiev, Users, organizationID, jumpcloud.com
dn: uid=ivan.koptiev,ou=Users,o=organizationID,dc=jumpcloud,dc=com
mail: ivan.koptiev@domain.com
sn: Koptiev
givenName: Ivan

# search result
search: 2
result: 0 Success

# numResponses: 2
# numEntries: 1
```

**Comment by nanoant** [comment]
@kop @Unknwon Okay then it may be the search scope problem not the filter. For some reason we test `userFilter` and `adminFilter` using `ScopeWholeSubtree` and this may be the reason JumpCloud refuses to return anything for such scope.

@kop Can you try:
~~~
ldapsearch -H ldaps://YOURLDAPSERVER -b uid=<username>,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
-W -D uid=<username>,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com -s base '(&(objectClass=inetOrgPerson)(uid=<username>))' uid givenName sn mail
~~~
And it it works, please remove `-s base`, this will work in subtree mode (same as currently Gogs), and see if it fails now.

**Comment by kop** [comment]
@nanoant, tested.

Again, I've used two different LDAP accounts for bind DN: `service.gogs` (aka `<bind username>`) and `ivan.koptiev` (aka `<username>`).

`service.gogs` has permissions to search LDAP. With this account data returned for both commands (with `-s base` and without it).

`ivan.koptiev` ( with this account I'm trying to enter Gogs) does not have LDAP search permissions, it always returns nothing.

**Comment by SergioBenitez** [comment]
Using the BindDN to search for the user's attributes may not be the best idea, @kop, @nanoant. The reason I implemented the LDAP BindDN authentication this way (binding as the user to search for his/her own attributes) is because the user is likely to have the most permissions on his/her own account details. The BindDN, on the other hand, should only have as few permissions as possible, which may mean only being able to read the users' CNs. As such, I suspect that switching this user attribute search account to be the BinDN will break many configurations, including my own.

@kop: Why not give user's search permissions, albeit limited ones so that they can at least search their own accounts? I'd say it's a configuration if a user can't search his own account.

**Comment by nanoant** [comment]
@kop @Unknwon Hmmzzz.... okay it seem then you are only allowed to bind but not to search, even your own attributes. Ouch that weird. This may be exactly the opposite to how the many other LDAP servers work, including mine.
In my case BindDN user is only capable to search using `mail` and `uid` attributes and retrieve them, this is safety measure and BindDN user is limited account. But User should be able to see all its own attributes, which is not the case of @kop.

**Comment by nanoant** [comment]
> Using the BindDN to search for the user's attributes may not be the best idea, @kop, @nanoant. The reason I implemented the LDAP BindDN authentication this way (binding as the user to search for his/her own attributes) is because the user is likely to have the most permissions on his/her own account details. 

@SergioBenitez Thanks for you feedback. Yeah I think your implementation is correct, with one exception I am not sure about is why we use `WholeSubtree` scope, I was just suspecting that JumpCloud was refusing to return anything because of that. But it seems it refuses to do any search even for own attributes, which is weird and wrong.

**Comment by SergioBenitez** [comment]
> Yeah I think your implementation is correct, with one exception I am not sure about is why we use `WholeSubtree` scope...

Why not? I used it mostly for completeness and to handle strange LDAP configurations where users may be nested several levels deep. If a user doesn't have permissions to read some subnode, the query results simply won't include information in those subnodes. This seems like reasonable behavior to me.

**Comment by kop** [comment]
@SergioBenitez,

I would be glad to allow users to search their own data, however, JumpCloud doesn't provide such ability. And I don't really want to work on own LDAP server, as it's an overkill for 5 man team.

They also have examples of configuration for Jenkins, Docker Registry, Wordpress, Apache and others, so I assume all this software is using Bind DN user (in fact have no idea, as I'm very new to LDAP).

I agreed, changing the way how LDAP auth is working in Gogs is a bad idea, but maybe it makes sense to add some config option that will solve problems with setups like mine?

**Comment by nanoant** [comment]
> If a user doesn't have permissions to read some subnode, the query results simply won't include information in those subnodes.
@SergioBenitez Agreed. But since the final (2nd) attribute search is done with UserDN base, does it really make sense for user node to have subnodes? I am not talking about BaseDN initial search to get UserDN for password check and attribute lookup, but the 2nd search in UserDN context.

But indeed any sane LDAP server shouldn't really care if subtree or just base scope is requested, and return what is allowed.

**Comment by nanoant** [comment]
> I agreed, changing the way how LDAP auth is working in Gogs is a bad idea, but maybe it makes sense to add some config option that will solve problems with setups like mine?

Reading https://jumpcloud.com/engineering-blog/how-to-connect-your-application-to-ldap/ seems JumpCloud does not really want regular users to be able to read their attributes.
@kop I think in such case there could be a check-box *read attributes using in BindDN context* (OFF by default) I can imagine many ppl want to use JumpCloud.

**Comment by kop** [comment]
@nanoant Agreed.

**Comment by SergioBenitez** [comment]
That's ridiculous and doesn't make much sense. It also encourages bad practices.

Does JumpCloud provide support? Perhaps you can ping them, @kop.

**Comment by kop** [comment]
@SergioBenitez Sure, they have support :)
I'll invite their representative to this thread.

**Comment by nanoant** [comment]
> That's ridiculous and doesn't make much sense (JumpCloud's policies, that is). It also encourages bad practices. Why give the BindDN so much permission?
I can imagine they don't want to give the regular users permission to read their own records, for some reason. But on the other hand, if somehow the BindDN user and pw leaks, then the whole user database can be dumped, if I understand correctly that JumpCloud Bind user can search for just anything.

@kop FYI the sane approach @SergioBenitez is talking, is to give BindDN user minimal search capabilities just to return DN for user matching some filter using limited set of attributes, eg. able to search only on `mail`. Assuming returned DN does not contain any sensible data. eg. is only numeric identifier, then even if somehow BindDN user and pw leaks, then this not let anyone the grab sensible data from LDAP. Altogether making BindDN user only be able to map email to DN (uid).

Even if JumpCloud changes their mind I don't believe they may introduce fix to their services anytime soon. So we may consider some quick and minimal workaround for Gogs (a checkbox LDAP config page), rather than blaming JumpCloud. At least for time being. WDYT?

**Comment by kop** [comment]
@nanoant Thank you for clarification. I got what @SergioBenitez was talking about, and I think I'm agreed with him - it would be interesting to hear something from JumpCloud team about why such policy is chosen.

But policies are theoretical stuff while in practice it would be very nice to have Gogs working with any possible LDAP configurations. I believe a switch to use BindDN for searching may be useful not only for JumpCloud - who knows what kind of weird configs and services people are using around the internet.

**Comment by codyjc** [comment]
@kop @SergioBenitez Joining on the discussion here from JumpCloud.  This is an interesting from our perspective, as we generally see two very well-established patterns over the hundreds of applications which have been configured with LDAP connectivity. Bind only for raw user/password authentication, and bind as a search user to scan the entire directory.  Our application is designed such that JumpCloud administrative users are required to flag at least one user as the LDAP binding user, however they may specify any users that they would like to have this privilege level at their discretion.

So from a policy standpoint, we try to build simply what our customers request and as of yet this will be our first request of this nature.

**Comment by Unknwon** [comment]
@codyjc thanks for joining the discussion. (I can see you just joined GitHub today :sweat_smile:)

**Comment by codyjc** [comment]
@Unknwon Ha, yeah just opened an account for JumpCloud specifically since I am a member of our customer success team.  Our engineering folks who I've been chatting with have been on here for quite some time and keep our https://github.com/TheJumpCloud up-to-date.  Still glad to be part of the discussion however and am happy to add any feedback I can from the team.

**Comment by Unknwon** [comment]
This is claimed to be implemented be merging https://github.com/gogits/gogs/pull/2634.

Please upgrade to latest `develop` branch to help test!

**Comment by kop** [comment]
Tested and it works:

```
2016/02/21 08:05:16 [T] LDAP will use BindDN.
2016/02/21 08:05:16 [T] Search for LDAP user: ivan.koptiev
2016/02/21 08:05:16 [T] Bound as BindDN uid=<bind username>,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
2016/02/21 08:05:16 [T] Searching for DN using filter (&(objectClass=inetOrgPerson)(uid=ivan.koptiev)) and base ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
2016/02/21 08:05:16 [T] Fetching attributes 'uid', 'givenName', 'sn', 'mail' with filter (&(objectClass=inetOrgPerson)(uid=ivan.koptiev)) and base uid=ivan.koptiev,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
2016/02/21 08:05:16 [T] Binding with userDN: uid=ivan.koptiev,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
2016/02/21 08:05:16 [T] Bound successfully with userDN: uid=ivan.koptiev,ou=Users,o=<organization ID>,dc=jumpcloud,dc=com
[Macaron] Completed /user/login 302 Found in 655.815669ms
```

**Comment by Unknwon** [comment]
:+1:

**Comment by Unknwon** [comment]
Close as fixed.
