### ISSUE TITLE
Image with link in markdown not working properly

### ISSUE THREAD

**Issue by bouffa** [gogits/gogs#2636]
Hi,

Image links in markdown are not working properly. Sometimes, the link is replaced with the image url.

For example, this markdown command :
`[![Project Stats](image_url)](link_url)`

**sometimes** produces a link to image_url instead of link_url :

`<a href=image_url><img src=image_url /> </a>`

instead of

`<a href=link_url><img src=image_url /> </a>`

The problem can be reproduced on https://try.gogs.io (Gogs Version: 0.8.37.0215):

https://try.gogs.io/chengbs/Openfire/src/3.10/README.md

The link of the first badge (travis-ci) is correct, but the second (openhub badge) is linking to the gif image.

[![Project Stats](https://www.openhub.net/p/Openfire/widgets/project_thin_badge.gif)](https://www.openhub.net/p/Openfire)

Thanks,

**Comment by Unknwon** [comment]
Right now, only image path ends with `.svg` will produce a link to link, not image itself...

**Comment by MrDark** [comment]
Found the same problem in the latest develop build (0.9.12.0316)

Markdown:
`[![Alt Text](http://image_url)](http://google.com)`
Html:
`<p><a href="http://google.com" rel="nofollow"></a><a href="http://image_url" rel="nofollow"><img src="http://image_url" alt="Alt Text"></a></p>`

For full example:
https://try.gogs.io/Mr_Dark/Markdown-Test/src/master/README.md

**Comment by Unknwon** [comment]
I think I said something very clear...

**Comment by DavidVentura** [comment]
I think the mimetype is wrong for svg images. When accessing a readme file with a linked svg image gogs offers a 'plain' file; even opening it just shows me the text because the mimetype is wrong

**Comment by strk** [comment]
Confirmed, this snippet also doesn't work on gogs:

```
[![build status]
(https://drone.osgeo.kbt.io/api/badges/geos/php-geos/status.svg?branch=master)]
(https://drone.osgeo.kbt.io/geos/php-geos?branch=master, alt=build status)
```

That is, it only produces the image, but not the link, as it should:

[![build status]
(https://drone.osgeo.kbt.io/api/badges/geos/php-geos/status.svg?branch=master)]
(https://drone.osgeo.kbt.io/geos/php-geos?branch=master, alt=build status)

**Comment by strk** [comment]
@Unknwon ending or not with .svg doesn't make a difference, see here:
https://try.gogs.io/strk/test1/issues/5

**Comment by strk** [comment]
Putting the image and link text onto the same line seems to fix the issue:

```
[![build status]
(https://drone.osgeo.kbt.io/api/badges/geos/php-geos/status.svg?branch=master)](https://drone.osgeo.kbt.io/geos/php-geos?branch=master, alt=build status)
```

[![build status]
(https://drone.osgeo.kbt.io/api/badges/geos/php-geos/status.svg?branch=master)](https://drone.osgeo.kbt.io/geos/php-geos?branch=master, alt=build status)

This is not a problem on github.

**Comment by strk** [comment]
I was wrong, single-line doesn't fix it either:
https://try.gogs.io/strk/test1/issues/5#issuecomment-948

**Comment by drm** [comment]
@Unknwon As I understand the rationale behind [the code][^1], it is there to have internally linked images being served from `raw` instead of `src`. But it also checks for links being absolute, i.e., have a protocol ([`validLinksPattern`][^2]).

It seems to me that there are two issues here:

* the processing should only occur for internal links, i.e., links that match the current working tree, or at least only the gogs instance. Can you maybe write up a list of test cases that should work, as you probably know better what the original reasoning behind the code was?
* On the other hand, if the link already is inside an `<a href...>...</a>`, then it would not make sense processing it at all. That would probably be a more robust fix anyway. Maybe the image render can do a reverse scan on the output buffer to check if there is an unclosed `a` tag already in the buffer.

[^1]: https://github.com/gogits/gogs/blob/master/modules/markdown/markdown.go#L186
[^2]: https://github.com/gogits/gogs/blob/master/modules/markdown/markdown.go#L46

**Comment by strk** [comment]
Meanwhile I've figured my own issue, and filed it as https://github.com/gogits/gogs/issues/3545

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/gogs/gogs.

**Comment by Unknwon** [comment]
Sorry, not develop branch, it's release/0.11.
