### ISSUE TITLE
Support differnt shape issue tracker IDs with RegEx

### ISSUE THREAD

**Issue by MoBe80** [gogits/gogs#2669]
In our issue tracker of choice (JIRA) we've got several project for different teams (Quality, Support, Development). These project have different "issue id formats" like QM-55, SUP-879 or DEV-357 they should redirect to  a URL like these https://_URL_/browse/DEV-357. So it would be great to take up the idea of @rojaro (in issue #890) again and implement a RegEx based issue ID identification.

**Comment by cstroe** [comment]
I'd like to work on this, but I need more information.
## Observations
### URL substitution
The external issue tracker URL can be injected in:
* A commit message on a repository's main page
![gogs-commit-list](https://cloud.githubusercontent.com/assets/1182093/14552578/6f022886-02a5-11e6-8e1b-86e2fb5d1ff5.png)

* The commit message at the top of the page when viewing an individual commit
![gogs-commit-view](https://cloud.githubusercontent.com/assets/1182093/14552637/bfe10e70-02a5-11e6-848b-ed90d99db581.png)

* Comments in a Pull Request
![gogs-comments](https://cloud.githubusercontent.com/assets/1182093/14552941/3c0dc7b6-02a8-11e6-91a7-5fa0ea8436e9.png)

### Substitution Pattern
Currently, the substitution pattern (regex) is fixed as `( |^|\()#[0-9]+\b`, so that anything that looks like #1234 is turned into a link.

### Configuring External Issue Tracker
External issue tracker URLs are configured on a per-repo basis, on the settings page of the repo.

![gogs-repository-issue-tracker-setting](https://cloud.githubusercontent.com/assets/1182093/14553024/c972de2a-02a8-11e6-9ef1-60d0b51f285b.png)

In addition to the `{issue}` number, there's a `{user}` and a `{repo}` substitution available for use in the External URL format.

## Done state
It seems like the simplest option to allow for creating JIRA URLs is to make the substitution regex configurable, per @rojaro's suggestion.

Does that sound right?

**Comment by MoBe80** [comment]
That is exactly what we need. It would be great if you could contribute you here. If you need someone for testing, let me know.

**Comment by cstroe** [comment]
@MoBe80, the pull request is ready for testing: https://github.com/gogits/gogs/pull/2992

**Comment by cstroe** [comment]
@MoBe80 this issue has been fixed, you can close it.
