### ISSUE TITLE
Cannot use apostrophe character

### ISSUE THREAD

**Issue by sarneeh** [gogits/gogs#2695]
## Installation info

- Gogs version (or commit ref): 0.8.43
- Git version: 1.9.1
- Operating system: Ubuntu 14.04 x64
- Database:
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite

## Description
I've just installed Gogs on my server, and i've got this problem:

![issue](http://i.imgur.com/tuKQndf.png)

What can I do to make the " ' " char look normally? I've changed it manually in database - it saves ok, but in the UI i'm still getting the same. Any ideas?

**Comment by zacheryph** [comment]
The error states that the name can only  contain alphanumeric + dash/dot.  This is purposely for a reason, not just cause.  apostrophe is not a valid character to use in the repository name.  This is due to the name being used for the repo AND the url's in accessing the repo.  I would recommend using a dash `-` or dot `.` instead of an apostrophe.  I also would recommend not manually editing the database as well.

**Comment by Unknwon** [comment]
Thanks your feedback!

But this is duplicated https://github.com/gogits/gogs/issues/1937
