### ISSUE TITLE
Always respond with go-import metadata when go-get=1

### ISSUE THREAD

**Issue by rschmukler** [gogits/gogs#2825]
## Description

When requesting a private repo with authorization credentials (eg. `Authorization: Basic ...`) it would be nice if gogs would respond with the relevant meta tags instead of redirecting via 302.

Alternatively, gogs could serve the meta tags regardless of whether the repo actually exists thereby mitigating the security concerns discussed in #816

**Comment by bradrydzewski** [comment]
I agree that if the same behavior is present for all repositories, even when the repository does not even exist, there would technically be no data leak. My proposal is if `?go-get=1` then always serve a page with `go-import` meta tags and return a 200 status code, even if the user is unauthenticated, and even if the repository does not exist

**Comment by Unknwon** [comment]
> When requesting a private repo with authorization credentials (eg. Authorization: Basic ...) it would be nice if gogs would respond with the relevant meta tags instead of redirecting via 302.

@rschmukler  Somehow, I think basic auth already works: https://github.com/gogits/gogs/blob/master/modules/auth/auth.go#L122

> My proposal is if ?go-get=1 then always serve a page with go-import meta tags and return a 200 status code, even if the user is unauthenticated, and even if the repository does not exist

@bradrydzewski any use cases?

**Comment by bradrydzewski** [comment]
We give the ability (with Drone) to authenticate with a netrc file. This enables cloning multiple private repositories over git+https without prompting the end user for a username / password. This works well because git uses curl under the covers which respects the authentication profiles defined by netrc files.

While there are multiple approaches to git authentication, the use of a netrc is pretty common and documented by most major hosting providers:
https://confluence.atlassian.com/bitbucketserver/permanently-authenticating-with-git-repositories-776639846.html

>  Somehow, I think basic auth already works: https://github.com/gogits/gogs/blob/master/modules/auth/auth.go#L122

Does this work with when using `{token}:x-oauth-basic`?

I am able to clone a private repository using the netrc, however, it seems to fail authentication when attempting the go get meta-data request with `?go-get=1`. This would lead me to believe that `go get` does not respect the netrc file, or that gogs does not support basic authentication at this endpoint using the oauth2 token (I am probably totally wrong here, but just trying to guess some possible root causes).

This is not an issue with private GitHub or Bitbucket repositories because the `go` tool does not make outbound http requests to these systems to fetch the  `go-import` metadata. This is because this information is already hard-coded into the go tool.

The workaround would be to use `git clone` instead of  `go get` to ensure the netrc file is used as seen below. This works for simple projects with a small number of dependencies, however, this may be onerous for a project with a large number of private repositories compared to using `go get ./...`

```diff
- go get gogs.foo.com/bar/baz
+ git clone gogs.foo.com/bar/baz.git 
```

**Comment by Unknwon** [comment]
@bradrydzewski thanks for the detail!

> Does this work with when using {token}:x-oauth-basic?

I think this is not supported, only standard format `Authorization: Basic xxx`.

> The workaround would be to use git clone instead of go get to ensure the netrc file is used as seen below. This works for simple projects with a small number of dependencies, however, this may be onerous for a project with a large number of private repositories compared to using go get ./...

OK make sense, let's wait for @rschmukler 's response.

**Comment by rschmukler** [comment]
Ah, I actually had only also tested it with Drone's injected `netrc` file (which uses `x-oauth-basic`). I have the same use-case as @bradrydzewski mentioned (as I actually ran into this while trying to get drone + gogs working with private gogs repos).

Another reason that this would be nice is that some of the tooling around vendoring also expect `go get` to work so relying on `git clone <repo>.git` can rule out using some of the tools, or at the very least require additional configuration (for example glide can be tricked into working with manually specifying VCS, but still logs warnings)

**Comment by Unknwon** [comment]
OK, maybe you want to change issue title to `Always response go-import metadata when go-get=1`?

**Comment by rschmukler** [comment]
@Unknwon done :+1:

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by fjorgemota** [comment]
Hey, is this already on `master`? How it's supposed to work?

I'm asking this because on private repositories it seems do not work on a docker container of Gogs, and at least on release notes of version v0.9.71 there is a mention of this issue as an improvement ("Always response with go-import metadata when ?go-get=1 #2825"), however..in this docker container, when trying with `Authorization: Basic ....` and without that header on a repository page it simply returns `<a href="/user/login">Found</a>.` without adding any `go-import` metadata...

Thanks for the great software, anyway. :)

**Comment by Unknwon** [comment]
Test on demo site as required.

**Comment by bkcsoft** [comment]
@fjorgemota You can't normally `go get` a private repository (for obvious reasons)
See this: https://gist.github.com/shurcooL/6927554

**Comment by wgriffiths** [comment]
Just in case this might be useful for someone else. 

All our repositories are private, but we wanted to use the go toolchain with as little friction as possible (and without adding .git at the end of all our imports). Since we already proxy Gogs with Nginx, I modified the config to return the "go-import"  content if the go-get query parameter is set. 

Tested with go get and it worked :)

**Example Config**
Just replace _git.domain.com_ with your domain. This assumes your using git over ssh.

```nginx
location ~ "(/[^/]+/[^/]+)(/.*)?" {
  if ($arg_go-get = "1") {
    return 200 '<html>\n<head>\n<meta name="go-import" content="git.domain.com$1 git git+ssh://gogs@git.domain.com$1"/>\n</head>\n<body>\ngo get git.domain.com$1\n</body>\n</html>';
  }
  proxy_pass http://localhost:3000;
}

location / {
  proxy_pass http://localhost:3000;
}
```

**Comment by Unknwon** [comment]
@wgriffiths I think it is working by itself? https://try.gogs.io/unknwon/404?go-get=1

**Comment by wgriffiths** [comment]
@Unknwon  I think the reason it doesn't work for us is that we have "Require Sign In View" enabled. 

If we run the following curl command that goes directly to gogs.

```bash
curl -i http://localhost:3000/org/repo\?go-get\=1
```

We get this response

```http
HTTP/1.1 302 Found
Location: /user/login
Set-Cookie: lang=en-US; Path=/; Max-Age=2147483647
Set-Cookie: i_like_gogits=fdae2c13d4d64a97; Path=/; HttpOnly
Date: Wed, 05 Apr 2017 21:27:25 GMT
Content-Length: 34
Content-Type: text/html; charset=utf-8

<a href="/user/login">Found</a>.
````

**Comment by Unknwon** [comment]
@wgriffiths I see... that is indeed complicated situation...
