### ISSUE TITLE
No mail notification when issue is closed/reopened

### ISSUE THREAD

**Issue by faouzzz** [gogits/gogs#2854]
Hi and thank you for Gogs !
I don't know if it is a bug or no.

- Gogs version (or commit ref): Gogs Version: 0.9.0.0306
- Git version: git version 2.6.1.windows.1
- Operating system: Windows server 2012
- Database:
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

When i push un project with a comment commit containing #ISSUE_NUMBER, this close automaticly the issue but does not notify the watchers of the project that the issue was closed.
...

**Comment by Unknwon** [comment]
Hi, where is example commit on demo site?

**Comment by faouzzz** [comment]
https://try.gogs.io/faouzzz/issue_2636/issues/2

**Comment by Unknwon** [comment]
What is the `notification` you are talking?

I can see https://try.gogs.io/faouzzz?tab=activity you have a news feed that says you closed issue 2

**Comment by faouzzz** [comment]
Mail notification

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by TheCherry** [comment]
Works, but only if you close the issue over the webview.
But the system send 2 emails if you comment+close, its will be better if it's merge that 2 E-Mails and send only one.

A close with a commit (aka close #XY), don't  work.
Here will it be nicely, if the system write a Mail with the commit + the info that the issue is closed.

**Comment by Unknwon** [comment]
@TheCherry Gogs version?
