### ISSUE TITLE
dark theme?

### ISSUE THREAD

**Issue by Nhoya** [gogits/gogs#2876]
Lot of us sometimes works at night and open the web page on a dark room is the same to penetrate your eyes with a sword, what about a dark and eye-relaxing theme?

**Comment by Unknwon** [comment]
Thanks your feedback, but this is out of the scope of Gogs core.

Please follow: https://github.com/gogits/gogs/issues/1126

**Comment by diveyez** [comment]
It is not out of the scope, just need a theme to be made. Ill make it.

**Comment by Kos-M** [comment]
hey , as many others i had to create a  theme my  own. (white is pain to our eyes in night)
![Capture2](https://user-images.githubusercontent.com/46938390/62416005-d2f35980-b63b-11e9-9454-e64b27079a54.PNG)
![Capture](https://user-images.githubusercontent.com/46938390/62415899-1056e780-b63a-11e9-9692-1448619adc91.PNG)



but the way i edit files is wrong and i know it because i eddited css files.(instead some .less) , i realized later , when i made the changes i just need to get rid of that white haha

what is your suggested method to overwrite default colors and styles ? 
i have changed gogs.css even on semantic ..
i would happy to share that , but needs to be done correctly..

**Comment by unknwon** [comment]
@Kos-M thanks for sharing! Actually, you can just inject your CSS file without touching the Git history: https://gogs.io/docs/features/custom_template#include-custom-css-file

**Comment by Kos-M** [comment]
@unknwon cool , i will create a repo just for that theme.
Im thinking it would be nice if exist on ui an element to controll active themes.
With a custom tenplate maybe..
What do you think ?

**Comment by unknwon** [comment]
@Kos-M that is definitely cool, but also is a complete feature, and basically a way to load custom CSS.

**Comment by Kos-M** [comment]
@unknwon it is i agree , but themes must change on the fly (depending users mood)..
since a theme is installed and available why to activate it must be complicated ?
p.s im thinking something like [this](http://akveo.com/ngx-admin/pages/dashboard)

**Comment by unknwon** [comment]
@Kos-M Maybe we should start a thread in the https://discuss.gogs.io, posting here will flooding others' inbox.
