### ISSUE TITLE
Git hooks not being executed

### ISSUE THREAD

**Issue by rudineirk** [gogits/gogs#2943]
- Gogs version (or commit ref): 0.9.13 (docker hub)
- Git version: 2.5.5
- Operating system: Fedora Linux
- Database:
  - [X] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:

## Description

Git hooks don't appear be executed on pushs, I tried adding a pre-push hook to prevent pushing to master, but it is not being executed

To debug I tried the following script on the pre-push hook:

```
#!/bin/bash
echo "test" > /tmp/test.txt
exit 1
```

It should have prevented any push, but I can push via https and ssh, it doesn't cause any effect

**Comment by Eeems** [comment]
My install of gogs executes git hooks. Have you made sure that the user gogs runs under (git on my server) has access to what you are trying to run?

**Comment by rudineirk** [comment]
I think so, I tried adding this https://dev.ghost.org/prevent-master-push/ hook via UI. That example in the first comment was to test if an error blocked a push.

**Comment by strk** [comment]
As I just had the same problem I recommend you check the executable bit of the hook files.
Gogs doesn't check for the hooks to be executables so won't notice if you (or anything else) drops the executable bit from the hook files.

@Unknwon is "checking permissinons" something you'd think appropriate for the code ? I guess it may help...

**Comment by Unknwon** [comment]
@strk Gogs does give `777` when update/create hook file: https://github.com/gogits/git-module/blob/master/hook.go#L98

**Comment by strk** [comment]
Those permissions are only set if the file did not exist:

From https://golang.org/pkg/io/ioutil/#WriteFile:
"If the file does not exist, WriteFile creates it with permissions perm; otherwise WriteFile truncates it before writing."

In my case I changed those file permissions manually, to not see them being set back to executable OR spotted as being disabled.

I think it would be useful to have a separate "enable"/"disable" setting based on file permission so that it is even possible to retain the code while temporarely disabling an hook.

**Comment by Unknwon** [comment]
> Those permissions are only set if the file did not exist:

If it creates with correct permission, how/why the permission changes after that?

**Comment by strk** [comment]
An external agent modifies the permissions, not Gogs.
Specifically, it was me doing that.

Note that you can enable/disable an hook by setting and
unsetting the execute bit. This is how git works. If Gogs
could use that same execute bit to turn the green light
on and off near an hook, and enable/disable it, that'd be
easier not to become out-of-sync with filesystem.

**Comment by Unknwon** [comment]
@strk I think you're not talking the original issue posted by @rudineirk ? The problem he/she has the hook script file somehow permission gets changed after creation.

**Comment by strk** [comment]
@Unknwon I don't see @rudineirk saying anything about file permissions (but yes, my comment was about my issue with hooks).

About Rudineis' issue: @rudineirk maybe your problem is just that Gogs is showing you more hooks than it would be supported by a git server. See #3007, and try using one of the server-side hooks (pre-receive, update, post-receive) instead.

**Comment by rudineirk** [comment]
@strk is right, I was trying to use a client side hook on the server side (pre-push), my mistake sorry.

I tried using the pre-receive hook and it worked as expected.
