### ISSUE TITLE
Commiter author should be gogs username, as on Github.

### ISSUE THREAD

**Issue by misuzu** [gogits/gogs#3099]
- Gogs version (or commit ref): 0.9.13.0318
- Git version: 2.8.1
- Operating system: Linux SMP Debian 4.3.5-1 (2016-02-06) x86_64 GNU/Linux
- Database:
  - [x] PostgreSQL
  - [ ] MySQL
  - [ ] SQLite
- Can you reproduce the bug at http://try.gogs.io:
  - [x] Yes (provide example URL): https://try.gogs.io/misuzu/username-test
  - [ ] No
  - [ ] Not relevant
- Log gist:

## Description

Commiter author should be gogs username, as on Github.

**Comment by Dasoren** [comment]
I do not want this change, or at lest not as the @misuzu asked for.
Reason: I use a lot of systems and want to know from what system I made the changes on. AKA: dasoren-ctl, dasoren-eps, dasoren-eff. The ctl, eps, eff are 3 of my systems. Those are the names setup in my .gitconfig file on each system.
When I do a push, I see that as the name on the commit and want to see it that way.

I understand why you want this change and can see why others would want this as well.
To who ever looks into this "issue/bug" please keep an option to use the name from the commiter as listed in the git commit message, rather than the gogs username.

**Comment by Unknwon** [comment]
So... what now?

**Comment by bkcsoft** [comment]
How about another user-setting? Either show full name OR username

**Comment by Unknwon** [comment]
@bkcsoft pre-user?

**Comment by Unknwon** [comment]
Duplicated to https://github.com/gogits/gogs/issues/2923?

**Comment by bkcsoft** [comment]
IMO yes :)

**Comment by Dasoren** [comment]
When you say "full name" you mean the name set in the git repo or some other name that is part of the user's data?

If this is going to be a thing, I would like an option to use the name set as the name in the git repo. Thanks.

**Comment by Unknwon** [comment]
Please follow on #2923
