### ISSUE TITLE
Invalid SSH clone URL

### ISSUE THREAD

**Issue by KeldorDE** [gogits/gogs#3199]
Gogs version: 0.9.13.0318
Git version: 2.1.4
Operating system: Rasbian ARM
Database: MySQL 5.5.44
Can you reproduce the bug at http://try.gogs.io: No, can't test the SSH clone (no password ;))

## Description

I'm using Gogs with the SSH clone URL. The URLdoes not work if I use upper case usernames and repository names.

**Example:**
Username: TestUser
Repository name: Test-Respo

This will produce the following SSH clone url:
`git@myhost.ext:TestUser/Test-Repo.git`

The folders on file system are created in lower case so SSH fails with the following error:

> fatal: 'TestUser/Test-Repo.git' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.

I think the clone URL should be in lower case regarding to the file system.

**Comment by tkausl** [comment]
What happens when you try to connect through ssh `ssh git@myhost.ext` ?

**Comment by KeldorDE** [comment]
The ssh Login prompt appears, if I Enter the Git Users password I can See the Contents of the Git Users home dir. If I translate the ssh Clone URL to lower case it works like a Charm, the Problem should Be the  lower case of the File System path

**Comment by tkausl** [comment]
No, it's not. You're not supposed to log into the git account using the credentials. Infact, you should disable password-login for the `git` user. You __need__ to use a rsa-key to connect which was added (the public-key) to gogs using the web-panel. _Do not_ connect with the credentials and _do not_ add the public-key manually to the authorized_keys file.

**Comment by KeldorDE** [comment]
Hi,

thanks for your response but it works when the username and the repo name is in lowercase. In my opinion it is still not a problem with key or password authentication. Please have a look at the following examples:

**This clone URL does not work:**
_This is the one I'm getting from the GOGs clone box._
`git clone git@myhost.ext:TestUser/Test-Repo.git`

**This clone URL works fine:**
_I've converted the clone URL to lower case_
`git clone git@myhost.ext:testuser/test-repo.git`

I hope the provided information makes the problem more clear.

**Comment by tkausl** [comment]
The clone URL __will__ work if you connect using a rsa key which you added to gogs. As I said, you're not supposed to login using the password, thats not Gogs's problem, if you want to connect using a method which is not supported by gogs and never will be.

**Comment by tkausl** [comment]
To understand why: When you add a public key to gogs, gogs will add a special entry to your authorized_keys file which tells your system, to invoke gogs as your login-shell instead of just bash or whatever, so gogs can check your read/write permissions to the requested repository and then redirect your traffic directly to this repository. In this case, the upper-case clone-URL does not matter as gogs _knows_ the real path to your repository. However, this will not work if gogs doesn't know who you are, neither if your system does not invoke gogs as login-shell at all. Therefore, you __have to__ connect using a key which you added through gogs, everything else will not work and opens security risks (as you have full control of the server, a key added through gogs has not)

**Comment by KeldorDE** [comment]
Thanks for explanation :) This makes sense, I'll give it a try.

**Comment by KeldorDE** [comment]
It works, thank you! I did not know that gogs has his one login-shell.
