### ISSUE TITLE
SSH / Cannot push with git/ssh from Server

### ISSUE THREAD

**Issue by mioga-brian** [gogits/gogs#3239]
Hello,
I have a ssh issue with my server (ubuntu trusty), when I try to git push a project from the same server where gogs is installed, which display this errors:

> fatal: 'user/repository.git' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

Note: From my computer git pushes works fine and gogs works well, too.

**Comment by Unknwon** [comment]
Post your SSH url.

**Comment by mioga-brian** [comment]
SHH Url: gogs@gogs.domain.de:user/repository.git

**Comment by Unknwon** [comment]
Thanks, how did you add your server SSH key itself?

**Comment by mioga-brian** [comment]
Yes, the HTTP-Url don't work also from my Server, but from my PC works the SSH-Url and the HTTP-Url.

**Comment by Unknwon** [comment]
>how did you add your server SSH key to itself?

I did not ask a yes/no question...

**Comment by mioga-brian** [comment]
> how did you add your server SSH key to itself?
>I did not ask a yes/no question...

Sorry, i'm abit tired. 
I did this:

> su gogs
> ssh-keygen -t rsa -C "gogs@domain.de"
> cat ~/.ssh/id_rsa.pub
> ssh-copy-id user@remote
> reload ssh
> restart ssh

**Comment by Unknwon** [comment]
Did you add SSH key through web UI?

**Comment by mioga-brian** [comment]
Yes, I added the SSH Key on the Web UI, it didnt work.

**Comment by Unknwon** [comment]
`Didn't work` are vague words.

**Comment by nbaum** [comment]
@mioga-brian FYI, when a key is added via the web UI it overrides the command executed when somebody logs in using that key so that gogs gets control over that SSH session.

_It doesn't remove existing keys_, so if your key was already in there - which it sounds like it was - OpenSSH would log you in normally using the existing entry in the `.ssh/authorized_keys` file. You'll have to manually remove that entry or, perhaps, use a different key when using git.

Note that you can't both use gogs via SSH _and_ log in normally into the same user _using the same SSH key_.
