### ISSUE TITLE
Links of pull request comment email should use pulls URL

### ISSUE THREAD

**Issue by Unknwon** [gogits/gogs#3401]
Currently what we have are still linking to `/issues/:index`, instead we should have `/pulls/:index` to be consistent.

**Comment by lstahlman** [comment]
Any preference on how it is implemented?

Some options:

- Handle everything in Issue.FullLink().  Pretty straightforward to do, but puts PR logic in Issue.
- Implement PullRequest.FullLink(), call instead of Issue.FullLink() if issue is a PR. More logical in some ways but also involves more code.

I have the second option working in my test environment.

**Comment by Unknwon** [comment]
Hi, I think it is OK to just make a `if issue.IsPull` inside `Issue.FullLink()`, since many logics on issue and pulls are basically the same. Also this way has the minimal change.
