### ISSUE TITLE
Remove +x permissions from static JS files

### ISSUE THREAD

**Issue by 18augst** [gogits/gogs#3458]
- Gogs version (or commit ref): 0.9.77.0814
- Git version: 2.8.3
- Operating system: all
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:

## Description
I propose to remove +x permissions from static JS files like:

    public/js/semantic-2.2.1.min.js
    public/js/libs/clipboard-1.5.9.min.js

... and others.

**Comment by Unknwon** [comment]
Reasons?

**Comment by 0xbaadf00d** [comment]
generally, it is worth noting that a good setup should not require files to have execute permissions. The files are not directly run, but rather are read into an interpreter or readed - only read permissions are needed to run a typical script (one that doesn't write anything).

The 'execute' permission on directories has a different meaning - it permits traversal without being able to read the contents. In order to be able to read a file in a directory, a user must have 'execute' permissions on EVERY directory above

**Comment by 18augst** [comment]
Thank you. I wanted to say the same thing, but you beat me

**Comment by Unknwon** [comment]
So what now?

**Comment by 18augst** [comment]
@Unknwon  Well if you do not care, I do not insist.

**Comment by Unknwon** [comment]
Yeah, of course I wouldn't bother unless strong prove of scenarios of security issue.
