### ISSUE TITLE
Keeping forks synchronized

### ISSUE THREAD

**Issue by JozefCulen** [gogits/gogs#3476]
Hello,

Is there possibility for adding functionality "automated fork syncing" (https://confluence.atlassian.com/bitbucketserver/keeping-forks-synchronized-776639961.html). 
It should do something like this (text from link):
>Note that syncing is about pulling recent upstream changes into your fork, whereas pull requests are about pushing your changes back to the upstream repository.

Issue #2770 is relevant for us too.

**Comment by Unknwon** [comment]
Hi, for `automated fork syncing`, no. You can just create another mirror repo from same Gogs instance.

**Comment by JozefCulen** [comment]
Hi, thanks for the reply. 

Problem is, that mirror is just read only. We want to be able to write to this fork. 
You can check URL in the first post for more details.

**Comment by 0xbaadf00d** [comment]
what is the point? Keeping fork synchronized automatically is not a trivial thing. By instance : how to manage merge error ?

It's still easier to use:
```
git checkout develop
git fetch upstream [--prune]
git merge upstream/develop 
```

**Comment by solsson** [comment]
#2235 is related, possibly just a subset. @Unknwon can't this issue remain open as a feature discussion? I'm +1 for gogs<->gogs synchronization.

@0xbaadf00d What we're looking for, in https://github.com/Yolean/kubernetes-git-cluster/, is basic failover for git clone. We accept that issues+PRs+wikis (despite #3233) lives on the leader instance.

Crucially, we want to push to the follower (mirror) instance so that we know that the two instances are in sync. Whenever you go to the leader to create a PR you expect the mirror to have re-pushed.

The bitbucket link by @JozefCulen is interesting. Maybe scope can be reduced further. For example with the simplified failover case the leader will only merge pull requests, never receive pushes.

Our best option now for failover - read-only mirror(s) - is to have them configured with 1 min interval using https://gogs.io/docs/advanced/configuration_cheat_sheet#cron---update-mirrors-(cron.update_mirrors). We'd have to manually verify that they are in sync, or make sure we set our remotes' `fetch` URL to the replica and `push` URL to the leader.

What could be accomplished with an option to disable #948 and a naive [post-receive](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#post-receive-ORTYi7ikiM) hook that attempts a push back to the "mirror of" URL? Or is there an extension point in the Go code for things to happen after push?
