### ISSUE TITLE
a green issue number on 0.9.13.0318

### ISSUE THREAD

**Issue by ChangePlaces** [gogits/gogs#3514]
I'm using 0.9.13.0318, and have created an issue and assigned it to a milestone. However, for some reason it appears in two milestones, and the number appears green in the issue list. I'm not able to get it to appear in just one milestone and the normal colour!

![green-issue](https://cloud.githubusercontent.com/assets/302031/17968688/0fd5c488-6ac6-11e6-9030-549e02d4a66b.png)

**Comment by ChangePlaces** [comment]
as an update, even with closing the issue, it's still showing

**Comment by bkcsoft** [comment]
Please try it on 0.9.71 which is the latest release

**Comment by Unknwon** [comment]
Please read https://github.com/gogits/gogs/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by ChangePlaces** [comment]
Hi Unknwon - I've submitted a few bug reports before - some which are still open today for around a year! I fail to see what I haven't done that the instructions in your link shows.

Why would  an issue number be styled differently?

**Comment by duckbrain** [comment]
This is the top result while looking for an answer to this question.

It appears the green indicates that the issue is unread. If the unread status is correct would be a different issue.

https://github.com/gogits/gogs/blob/66c1e6b0e8308068dbddaec03585f388875f4192/templates/repo/issue/list.tmpl#L104
