### ISSUE TITLE
Move commits and releases tab one down

### ISSUE THREAD

**Issue by gsantner** [gogits/gogs#3518]
- Gogs version (or commit ref): 0.9.85.0824
- Git version: 2.1.4
- Operating system: Deb 8
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [ ] No
  - [x] Not relevant
- Log gist:
## Description

Please move the tab "Commits" to the row of the branches. 
I'm always wasting a lot of time looking fot the commits tab, because every git webui I used before have Branches and Commits on the same (bottom) line.

Current:
![bildschirmfoto von 2016-08-26 09-48-03](https://cloud.githubusercontent.com/assets/6735650/17998123/126f9914-6b73-11e6-9669-20edfaad8ecb.png)

Expected:
![bildschirmfoto von 2016-08-26 09-48-03 kopie](https://cloud.githubusercontent.com/assets/6735650/17998127/1af1f438-6b73-11e6-8c15-2865e28fa49a.png)

Just for ref: (GitHub)
![bildschirmfoto von 2016-08-26 09-56-13](https://cloud.githubusercontent.com/assets/6735650/17998208/70f1ffae-6b73-11e6-82cb-ff22256efe80.png)

Just for ref: (GitLab)
![bildschirmfoto von 2016-08-26 09-56-06](https://cloud.githubusercontent.com/assets/6735650/17998270/c6b93416-6b73-11e6-99ac-6fc45c4cc94a.png)

Please lets discuss about this. I would really appreciate if this would be done, and would save me and other people working on my gogs some time.

**Comment by Unknwon** [comment]
Thanks, I think you should rename title to move down `releases` as well. I prefer go GitHub way.

**Comment by gsantner** [comment]
@Unknwon  Thanks for feedback, great to hear that, I am also for moving `releases` aswell.

**Comment by bkcsoft** [comment]
Just adding my voice to this, I agree that Commits should be moved down because currently there's a UI-bug (inconsistency) related to that.
If you go to `Commits`, select a branch (not master) and go to `Code` you're back at master. Though if you select another branch under `Code` and go to `Commits` the correct branch is selected :confused:
Moving it down to to be a sub-page of `Code` would have them actually linked, and I can file a real bug-report for this :laughing: (I will anyhow :wink:)

On the other hand, `Releases` shouldn't be moved down IMO, since they are not linked to `Code` in the same way commits are.

**Comment by gsantner** [comment]
`Commits` should be moved yeah, `Releases` can, but it's no must.
Sure there is an relation:

Branches = multiple timelines of code
Commits = one timeline of code
Releases = point in an timeline of code

**Comment by Unknwon** [comment]
Note: Should add branches at the same time.

**Comment by Unknwon** [comment]
Related: https://github.com/gogits/gogs/issues/4154

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io/gogs/gogs.

**Comment by gsantner** [comment]
@Unknwon
Thanks!

**Comment by Unknwon** [comment]
No problem.

Right now only two items look somewhat strange, but will be fine once we have **branches** and **contributors**.
