### ISSUE TITLE
Login Admin User,Http500

### ISSUE THREAD

**Issue by qiqizjl** [gogits/gogs#3605]
- Gogs version (or commit ref): V0.9.97
- Git version:  1.7.1
- Operating system:  Centos6.8 64Bit
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist:
  2016/09/06 11:43:44 [D] CSRF Token: SrHRfZplDfhtmF4XSp9xRnQ58oM6MTQ3MzEzMzM4Nzc4NTc5NTMwNw==
  [Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
  /usr/local/go/src/runtime/panic.go:458 (0x434743)
  /usr/local/go/src/runtime/panic.go:62 (0x43329d)
  /usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
  /home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9)
  /home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd)
  /home/vagrant/gopath/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x8cc303)
  /usr/local/go/src/runtime/asm_amd64.s:480 (0x4645ec)
  /usr/local/go/src/reflect/value.go:434 (0x4f6148)
  /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
  /home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
  /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
  /usr/local/go/src/reflect/value.go:434 (0x4f6148)
  /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
  /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
  /usr/local/go/src/reflect/value.go:434 (0x4f6148)
  /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
  /usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
  /usr/local/go/src/reflect/value.go:434 (0x4f6148)
  /usr/local/go/src/reflect/value.go:302 (0x4f5a64)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
  /home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
  /home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
  /usr/local/go/src/net/http/server.go:2202 (0x70144d)
  /usr/local/go/src/net/http/server.go:1579 (0x6fde57)
  /usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
  [Macaron] 2016-09-06 11:43:44: Completed /user/login 500 Internal Server Error in 15.879042ms‘
  Description

...
I update GogsV0.9.97 from GogsV0.9.71.
now ,I do not Login Admin User ,http return 500. But other user is ok,login success;

**Comment by rugk** [comment]
@qiqizjl  Please read your post again. Have a look at the **bold** printed part! :warning:

**Comment by beppler** [comment]
I have the same problem, using a valid user and cloning a repository.

```
[Macaron] 2016-09-09 08:27:47: Started GET /gti/fenix.git/info/refs?service=git-uplo
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:458 (0x434743)
/usr/local/go/src/runtime/panic.go:62 (0x43329d)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd
/home/vagrant/gopath/src/github.com/gogits/gogs/modules/auth/auth.go:129 (0x803531)
/home/vagrant/gopath/src/github.com/gogits/gogs/modules/context/context.go:165 (0x84
/usr/local/go/src/runtime/asm_amd64.s:481 (0x4646b6)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
/usr/local/go/src/net/http/server.go:2202 (0x70144d)
/usr/local/go/src/net/http/server.go:1579 (0x6fde57)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
```

**Comment by shaneHowearth** [comment]
I have the same problem:

[Macaron] 2016-09-11 14:57:30: Started POST /user/login for 219.88.237.226
2016/09/11 14:57:30 [D] Session ID: b2032e7334f39eef
2016/09/11 14:57:30 [D] CSRF Token: wVa0ToyHadjbldxa1IpuRvutgrg6MTQ3MzU2MjA5MjQ4MTkyMjU0OQ==
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:458 (0x434743)
/usr/local/go/src/runtime/panic.go:62 (0x43329d)
/usr/local/go/src/runtime/sigpanic_unix.go:24 (0x449644)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491 (0x5609a9)
/home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:549 (0x560fbd)
/home/vagrant/gopath/src/github.com/gogits/gogs/routers/user/auth.go:107 (0x8cc303)
/usr/local/go/src/runtime/asm_amd64.s:480 (0x4645ec)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/github.com/go-macaron/session/session.go:186 (0x74d665)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/recovery.go:161 (0x7f642b)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:104 (0x7e3316)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/logger.go:43 (0x7f55fe)
/usr/local/go/src/runtime/asm_amd64.s:479 (0x46453c)
/usr/local/go/src/reflect/value.go:434 (0x4f6148)
/usr/local/go/src/reflect/value.go:302 (0x4f5a64)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:177 (0xb1a2f3)
/home/vagrant/gopath/src/github.com/go-macaron/inject/inject.go:137 (0xb19cb2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/context.go:113 (0x7e33f2)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:184 (0x7f77bc)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/router.go:286 (0x7ef98e)
/home/vagrant/gopath/src/gopkg.in/macaron.v1/macaron.go:177 (0x7e7cab)
/usr/local/go/src/net/http/server.go:2202 (0x70144d)
/usr/local/go/src/net/http/server.go:1579 (0x6fde57)
/usr/local/go/src/runtime/asm_amd64.s:2086 (0x4670a1)
[Macaron] 2016-09-11 14:57:30: Completed /user/login 500 Internal Server Error in 3.076533ms
[Macaron] 2016-09-11 14:57:31: Started GET /favicon.ico for 219.88.237.226
2016/09/11 14:57:31 [D] Session ID: b2032e7334f39eef
2016/09/11 14:57:31 [D] CSRF Token: wVa0ToyHadjbldxa1IpuRvutgrg6MTQ3MzU2MjA5MjQ4MTkyMjU0OQ==
[Macaron] 2016-09-11 14:57:31: Completed /favicon.ico 304 Not Modified in 446.205µs

The issue is at /home/vagrant/gopath/src/github.com/gogits/gogs/models/login_source.go:491

**Comment by Ritbit** [comment]
Same here.

I'm using v0.9.97, rolling back to 0.9.71 resolved the issue.
Using postgres 9.5 and LDAP (binddn) authentication. 
I tried sqlite and PAM too but all combinations showed the same result with a similar error log as shown above.

**Comment by bkcsoft** [comment]
The error is here: (models/login_source:491)
```go
func ExternalUserLogin(user *User, login, password string, source *LoginSource, autoRegister bool) (*User, error) {
	if !source.IsActived { // <-- Here...
		return nil, ErrLoginSourceNotActived
	}
```
`source` is never checked for `nil` even though it's a pointer...

But the actual problem lies in here: (models/login_source:543)
```go
	sources := make([]*LoginSource, 0, 3)
	if err = x.UseBool().Find(&sources, &LoginSource{IsActived: true}); err != nil {
		return nil, err
	}

	for _, source := range sources {
		authUser, err := ExternalUserLogin(nil, username, passowrd, source, true)
		if err == nil {
			return authUser, nil
		}

		log.Warn("Failed to login '%s' via '%s': %v", username, source.Name, err)
	}
```
AFAIK `source` should not be able to be `nil` :worried:

**Comment by rugk** [comment]
@bkcsoft Why not create a PR?

**Comment by qiqizjl** [comment]
@Unknwon

**Comment by rugk** [comment]
BTW on GitHub you can [link to file lines](https://github.com/gogits/gogs/blob/7c1fbed05764ff27c0684df92961a030e2e3344b/models/login_source.go#L491).

**Comment by bkcsoft** [comment]
@rugk I was to lazy to do that (and GH could/should do that automagically!) :trollface:

**Comment by 2ion** [comment]
I'm seeing the exact same issue with 0.9.97, on sqlite, after gogs ran perfectly for a little over a month.

Clearing all cookies and saved logins in the browser used for signing in makes be able to log in again to the web interface again…

**Comment by Unknwon** [comment]
I believe this is fixed in https://github.com/gogits/gogs/commit/7c1fbed05764ff27c0684df92961a030e2e3344b which is right after 0.9.97 release.

**Comment by juusechec** [comment]
For previous version I replace de binary file "gog" and templates directory to solve de issue.
