### ISSUE TITLE
Webhook and sha256 hmac

### ISSUE THREAD

**Issue by rjes** [gogits/gogs#3692]
Hello!

Instead of sending the Webhook secret in cleartext (it's cleartext even if the transports is protected by https) we should do as github does and create a hmac of the payload.
There are at least two benefits of this:
1. The webhook secret is protected when in transfer
2. The payload hasn't been tampered with

The most important thing is number 2 (but if the webhook secret is picked up on the wire, the number 2 is almost a fact), webhooks are often used for continue (integrations|deployments).
A theoretical attack could be to trigger a build+deploy of an older version of a software that contains security-related bugs.

I can try to create a pull request, but I can not guarantee that the code will look good and elegant (I'm a novice in Go). 
Do you think this is a feature to add (and want to do it yourself) or has it been rejected in the past, and why in that case?

This is the python version of the code:
import hmac
mac = hmac.new(webhook_secret, msg=payload, digestmod=hashlib.sha1)

//Robert

**Comment by FSMaxB** [comment]
So as far as I understand you want to change how the verification of the webhook secret works (the way that the other party proves the fact that it knows the secret).

It sounds like a good idea to not send the secret over the wire directly because it is not necessary to do so.

Let me explain my understanding:
1. Take the payload of the webhook request.
2. Create a message authentication code (MAC, doesn't have to be HMAC) with the Webhook secret as it's key. (this is done by the sender and receiver (once the receiver got the message))
3. Send the message payload and MAC.
4. If the MAC is identical on both sides, both sides have the same webhook secrect  **and** the same message payload.

Even though HMAC is quite resistent to collisions in the underlying hash function, maybe it is a good idea not to use SHA1 in which more and more flaws are discovered..

**Comment by rjes** [comment]
Hi!
You got me right, that workflow is how I imagine the things should be done.
And yes, we should maybe use sha256 or 512 instead of sha1.
I think I have some learning to do before I contribute with code ;)

**Comment by bkcsoft** [comment]
GitHubs Webhooks (which Gogs tries to be compatable with) says this:
> **secret**: An optional string that's passed with the HTTP requests as an X-Hub-Signature header. The value of this header is computed as the HMAC hex digest of the body, using the secret as the key.

So I agree that Gogs should be changed to reflect this :+1: 

Source: https://developer.github.com/v3/repos/hooks/#example

**Comment by Unknwon** [comment]
Note: https://play.golang.org/p/wteqLNcnTV

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `release/0.11` branch or https://try.gogs.io.

![image](https://cloud.githubusercontent.com/assets/2946214/23293280/4451fd9c-fa33-11e6-8706-8a587b54cec9.png)
