### ISSUE TITLE
Feature suggestion - loading progressbar on Gogs

### ISSUE THREAD

**Issue by joubertredrat** [gogits/gogs#3693]
Hi guys,

This is a small Feature suggestion for Gogs UX. On my projects, I use page loading progress bar and is simple to use, similar from Youtube, when page is loading, is possible to see loading progressbar on top page.

I use [this plugin ](https://github.com/HubSpot/PACE) with theme `Flash` and worked very fine here. 

What you think?

**Comment by bkcsoft** [comment]
We have very few ajax-requests :sweat:

**Comment by LefsFlarey** [comment]
@bkcsoft [This might be interesting](http://github.hubspot.com/pace/docs/welcome/)

**Comment by Unknwon** [comment]
It's a fancy idea but I don't Gogs actually need this at v1. Currently Gogs use as static page as possible to simplify (mainly because I don't very good at front end and still learning).

Only some critical task like [migration would add a loading icon while process in the background](https://github.com/gogits/gogs/issues/829).
