### ISSUE TITLE
LDAP Authentication with '@' in Usernames

### ISSUE THREAD

**Issue by mmaier2** [gogits/gogs#3694]
Hi,
- Gogs version (or commit ref): 
  v0.9.71
- Operating system: 
  RHEL7, Openldap
## Description

For some reason we have '@' in our usernames (uid), like a.b@c
For a testuser without '@' LDAP authentication/login works. 
For users with '@'  I'm getting an login error. 
So I guess if the username contains an '@' it is regarded as an email?

Users are located within an ou=users,... 
and filter is (&(objectClass=posixAccount)(uid=%s))

Thanks
Markus

**Comment by chrisipa** [comment]
We have the same problem in our organization.

+1

**Comment by mbeck-** [comment]
I can confirm that. We can't authenticate using the krb5PrincipalName LDAP attribute (in addition to uid) for that reason (Kerberos principal names use "@" as the realm separator).

According to the log the resulting LDAP filter looks correct and the authentication is successful ("Bound successfully with userDN..."). But I get the login form again.

**Comment by skorhone** [comment]
This might be silly question, but why would you prefer krb5PrincipalName over uid / cn? I think the real problem might not be ldap authentication, but authentication in general. If you check login form it allows you to login with either username or with email. Username with @ might get interpreted as an email during login

**Comment by mbeck-** [comment]
@skorhone I don't prefer it it over uid/cn, but I usually allow several attributes ORed in an LDAP filter (e.g. uid, kr5PrincipalName, mail etc.). That way the user is free to choose what to use as login. But the real advantage is that it's possible to use multiple authentication methods with a single user database, if the applications supports this. To give a practical example: With applications supporting this (Dovecot, Grafana and many others) we use Kerberos/GSSAPI authentication (secure and convenient, very common in enterprises) but sometimes allow other authentication methods as fallback. By using multiple attributes ORed in an LDAP filter, we are still able to map this to the correct identity, regardless of the authentication method used (in which case an application might see different IDs).

I think it's wrong to assume a different attribute just because a certain character appears in a login. If someone wants to allow either uid or email to be used as a login name, than this should be done with an LDAP filter (with ORed attributes).

**Comment by Unknwon** [comment]
Merge this into https://github.com/gogits/gogs/issues/4827.
