### ISSUE TITLE
No wiki for migrated repo

### ISSUE THREAD

**Issue by cracker0dks** [gogits/gogs#3792]
Hey,
I use the latest Dockerversion of Gogs and migrated a lot of repos successfully. But all of them have no wiki and are showing error 500 when I want to visit the wiki.
The Server log shows: 
`2016/10/21 03:02:24 [...routers/repo/wiki.go:54 renderWikiPage()] [E] GetBranchCommit: object does not exist [id: refs/heads/master, rel_path: ]
`

If I make a new test repo iside the gogs page, I can add a wiki as intended.

Is this my fault? How can I add a wiki to a migrated repo?

Thanks :)

PS: I dont want to migrate the wiki... I just want to be able to add a new one after code migration.

**Comment by wytzevanderploeg** [comment]
I have the same problem and it appears that the migrated wiki repositories do not have a master branch. (located next to the original repository in the gogs repositories folder)

When I run a `git branch` I do not see a master branch in the migrated repositories. Which is confirming what the error log states.

Since I only have empty wiki's my workaround was to delete the existing/migrated wiki repository and copy the one from the locally created test project which does have a master branch.

**Comment by 512gbyte** [comment]
+1

**Comment by ubiko** [comment]
@512gbyte I had the same issue, you need to update your server's git version. I think it needs to run `2.7.1` or higher.

I was running `1.5*` something, deleted the .git, created a new repo, pushed and every works as intended.

Hope this helps

**Comment by 512gbyte** [comment]
git version is 2.7.4. this is running on aws (ubuntu-server-16.04)..

**Comment by ubiko** [comment]
@512gbyte that's strange..I had the exact same error and problem as you and updating fixed it. Can you try upgrading it more? I'm currently running `git 2.8^` . I'm sure you've tried already but just in case, since you mentioned you're migrating from previously existing gits,

1. In admin settings -> Rewrite all hooks.

2. Create a new repository from scratch, try creating a wiki.


I doubt No.2 will work but doesn't hurt to try ¯\_(ツ)_/¯

**Comment by 512gbyte** [comment]
thanks for reply!
i choose No.2 options, wiki is not important but i just want to notice this case. :smile: 
i really satisfied 'gogs'!

**Comment by ubiko** [comment]
@ghost so it worked?

**Comment by cracker0dks** [comment]
Ok, I got a workaround for the 500 Error.
Go to the repo -> settings and delete all wiki data
Then you have to activate the wiki function again. 
Now you can use the wiki without problem 👍

**Comment by Unknwon** [comment]
@cracker0dks where did you migrate from? Gogs tries to clone related wiki repository if exists, see https://github.com/gogits/gogs/blob/master/models/repo.go#L640-L650

**Comment by jxsl13** [comment]
Same issue, migrated from gitlab.com
cracker0dks' workaround works, for now :)

**Comment by Unknwon** [comment]
Failed from gitlab.com because I think it always requires a password? I can migrate any public repo with wiki from GitHub without any problem.

**Comment by jxsl13** [comment]
I mean that even tho no wiki got migrated (btw. I had no wiki), you don't get the page to create a new wiki entry, but instead a 500 error.

**Comment by Unknwon** [comment]
@jxsl13 can you create an example on demo site? (500 on wiki after migration)

**Comment by jxsl13** [comment]
@Unknwon https://try.gogs.io/jxsl13/info-a/wiki

**Comment by Unknwon** [comment]
@jxsl13 Thanks! What is the source URL so I can perform clone on my machine?

**Comment by jxsl13** [comment]
was actually a private project on gitlab: made it public https://gitlab.com/jxsl13/Informatik-A

**Comment by Unknwon** [comment]
I might know the problem: Gogs detected that there is a wiki, but failed to clone and didn't clean up the directory. Will check on that, thanks for the info!

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.
