### ISSUE TITLE
Fail to test 'git' command: exec: "git": executable file not found in $PATH

### ISSUE THREAD

**Issue by Veitor** [gogits/gogs#3911]
- git version : 2.2.1
- Gogs version: 0.9.1

error info: 
[.../gogs/models/repo.go:114 NewRepoContext()] [E] Fail to test 'git' command: exec: "git": executable file not found in $PATH (forgotten install?)

I just update git client from 1.7.1 to 2.2.1, then run gogs and report this error message.
I have added git to the $PATH,  and the run user is `git` not `root`
Where did it go wrong?

![1](https://cloud.githubusercontent.com/assets/7483890/20660883/cc8bb73a-b586-11e6-940b-f5d3491e3657.jpg)

**Comment by Veitor** [comment]
the question  #2839  i have found, but still not solve this promble.

when i switch `git` user, i just run `./gogs web` is ok.
but when i is `root` user, i run `service gogs start` is not effective and report error message

**Comment by Veitor** [comment]
i have solved this promble.
蛋疼，竟然是gogs要求git需要放在`/bin/git`，我觉得这个问题可以写在官网文档中的常见问题里，另外官网真的很卡，一个下午才只能打开两三次，我都翻墙了也难打开，很无语

**Comment by a83518485** [comment]
感谢.. 这问题. 坑我大半天. 真是吐了. 强烈建议 在官网写清楚. 不去看源码 . 要坑多少人

**Comment by Lord0** [comment]
I had the same issue when trying to start Gogs from supplied init.d script. I had to add Git location (/usr/local/bin) to PATH in script

**Comment by Chupaflo** [comment]
I had the same issue after installing a new git version "on top" of the current one, on windows. 
It took me a while to solve it because I'm not admin on my computer and I could not change the PATH variable.
To solve it I did a clean uninstall of git (via uninstall software from config panel) and then reinstalled it, and it works again. (the git.exe is now in the PATH variable, without needing admin rights during install, that must be magic operating here)
