### ISSUE TITLE
Possibility for notify when commit

### ISSUE THREAD

**Issue by LeDistordu** [gogits/gogs#3938]
It's possible to add possibility on repo to notify when commit ?

**Comment by ooxi** [comment]
Gogs does support [webhooks](https://gogs.io/docs/features/webhook) therefore it's quite easy to get push notifications from gogs. Commits are a local thing in git, if you *really* need commit notifications instead of push notifications, you should look at [`post-commit`-Hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks#Client-Side-Hooks) in your local `.git` directory.

**Comment by bkcsoft** [comment]
@ooxi `post-commit`-Hook is a client-side hook so it will not be fired by Gogs

**Comment by ooxi** [comment]
@bkcsoft yes, that's exactly what I said. But maybe I was not intelligible enough, thanks for the clarification :)

**Comment by Unknwon** [comment]
I think this should be closed... either webhook or `post-receive` can be used for custom notifications.
