### ISSUE TITLE
Search in private repositories feature

### ISSUE THREAD

**Issue by romanvbabenko** [gogits/gogs#3947]
Please add ability to search through the private user repositories owned by current user.
As time goes on numbers of them grows and it's really hard to find something you need.
Just simple text input on top of owned reps list or whatever you decide be proper for that.

Thanks a lot

**Comment by georgesuba** [comment]
@romanvbabenko hi, you can make them all public and search via search bar - but if you would like to still keep them private, you can modify the templates which comes with gogs, - I did not know any go language but I understand it right a way.. unknown made brilliant idea to base templates on this!

...otherwise I am afraid, you would have to use repos function in admin.. perhaps this can be done easy to modified too..so normal user can search via private repos as well..private for logged in user means bad idea.. so its understandable that only admin can do so.. 

- in my case I wanted to give clients access to software however it need it to be completely private, so public repos for clients as they dont need to use password when clone etc.. this makes things much easier however name your repos carefully - if repo is public and anyone can guess the name of that repo, he will have access.. keep in mind that you will have to know repos link at any time. This way you can still be semi private :)

Private repos of course only via log in option.. - btw once use is logged in, all functions of gogs are normal as usually. I made some simple video for you.. [video is here.](https://youtu.be/DLFnu6KD6O4)

**Comment by MarcelSimon** [comment]
Please add this feature, it is so annoying to not be able to search if you have access to 50+ repos including repos from organizations.

**Comment by glothriel** [comment]
Isn't this closed by https://github.com/go-gitea/gitea/pull/222?

**Comment by psaavedra** [comment]
Hi @Unknwon what about this issue. is there anything where I could help?  What about the https://github.com/go-gitea/gitea/pull/222 in gitea fork. Maybe I could work in adapt it to Gogs. Let me me know your point of view.

**Comment by Unknwon** [comment]
@psaavedra hi, just realized this is duplicated to https://github.com/gogits/gogs/issues/3088 because explore is the only place we can search for repository right now.

go-gitea/gitea#222 has some changes I have no ideas of what those do.

I'll prioritize #3088 to current release cycle.
