### ISSUE TITLE
Panic when login via PAM

### ISSUE THREAD

**Issue by sbarre-esit** [gogits/gogs#4216]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 1.8.3.1
- Operating system: RHEL 7.3
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [X] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`): https://gist.github.com/stevenbarrehpas/e48ae270893e180092ff067f9efdb0e1

## Description
500 error when logging in with LDAP

**Comment by Unknwon** [comment]
Hi, from the log, you are using PAM not LDAP?

**Comment by stevenbarrehpas** [comment]
Correct, PAM. And pam is using winbind.

**Comment by Unknwon** [comment]
OK,... github.com/msteinert/pam seems no longer maintained and error is from this package. I have no idea...

**Comment by stevenbarrehpas** [comment]
It was working fine yesterday on 0.9.128.0131 and seems to have only broken after the update.

**Comment by Unknwon** [comment]
I see. Maybe it stops working with Go 1.8.

**Comment by ichrispa** [comment]
Hi all.

I can confirm this error is also present with Go 1.7.5.

* Gogs version (or commit ref): 0.11.6.0407
* Git version: 1.7.10.4
* Operating system: Debian 7 (Wheezy )

Compiled with -tags "pam sqlite".

This is annoying. Gogs is kind of in my sights because I want to not use LDAP... any chance to get this fixed? 

Best regards and thanks in advance for your support,

ichrispa

**Comment by ichrispa** [comment]
Hi again @Unknwon and @sbarre-esit,

I did get PAM working after some fiddling, but this is the first time I ever handled go. So I am really not confident enough to put this into a pull request.

Here's how I got PAM running:

1. replaced vendor/github.com/msteinert/pam with the actual git clone of his repo. The reason was that his transaction_test.pam is actually working. Lo and behold, this made any errors go away. Authentication still failed.
2. My /etc/pam.d/gogs is cloned of an interactive login (ssh). But gogs does not pass a username to pam echo-on prompts. So I extended the switch in the callback of  pam.go a bit:

```
func PAMAuth(serviceName, userName, passwd string) error {
	t, err := pam.StartFunc(serviceName, userName, func(s pam.Style, msg string) (string, error) {
		fmt.Printf("Callback called\n")
		switch s {
                case pam.PromptEchoOn:
                        return userName, nil
                case pam.PromptEchoOff:
                        return passwd, nil
                case pam.ErrorMsg, pam.TextInfo:
                        return "", nil
                }
		return "", errors.New("Unrecognized PAM message style")
	})

	if err != nil {
		return err
	}
        
        fmt.Printf("Got PAM started\n")
	if err = t.Authenticate(0); err != nil {
                fmt.Printf("t.Authenticate(0) failed\n")
		return err
	}

	return nil
}
```

This is working as expected. Authenticates valid users, rejects buggy credentials.

I have no idea how to get go to fetch the current master of @msteiner's repo for regular builds, but that fixes the Pointer-error.

As for the patched switch-statement, I might have a weird concept of how this is supposed to work. Maybe supressing the username here is normal? Is it possible to either provide a pam.d service description that works with the non-interactive prompt?

Best regards, 

ichrispa

**Comment by Unknwon** [comment]
@ichrispa thanks for the patch! Maybe you could send a PR so I can closely look what changes you made?

**Comment by Unknwon** [comment]
Vendor has been updated on both `master` and `develop` branch, please help test.

**Comment by msteinert** [comment]
Did this end up being a problem with github.com/msteinert/pam?

It isn't necessarily unmaintained; The PAM API hasn't changed much lately.

**Comment by Unknwon** [comment]
@msteinert No.. I think it was caused by, somehow, govendor vendors an old (buggy) version of that package. Force update and then vendor again seems fixed the problem.

**Comment by ichrispa** [comment]
Hey @Unknwon,

without knowing/learning go's build system, I have no idea how to create a meaningful build request. But just updating the msteinert/pam dependency to the current version fixed the problem.

Thanks a lot for your support 👍 

ichrispa
