### ISSUE TITLE
Error 500 while trying to load dashboard

### ISSUE THREAD

**Issue by c00ldchan** [gogits/gogs#4231]
- Gogs version (or commit ref): 0.10.1.0228
- Git version: 2.1.4
- Operating system: Ubuntu 14.04
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [x] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No(works only for admin users)
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

## Description
Steps to reproduce: 
1) Login as admin user
2) Create organization
3) Delete organization 

Result: error 500 while loading dashboard. 
I've managed to fix that by removing entries in org_user table for admin user. 

Regards, 
Vlad.

**Comment by codecrafting-net** [comment]
I found out what is going on. The problem is the missing references on deleting organizations on database. The error that was causing to me on the log was:

`[...routers/user/home.go:47 getDashboardContextUser()] [E] GetOrganizations: user does not exist [uid: 14, name: ]`

I managed to solve the problem opening the database file gogs.db (I uses SQLite Browser). The organization is deleted on table user, but not his referecences on table org_user which cause the missing user (ie organization).

**Comment by Unknwon** [comment]
@codecrafting-net The relation is deleted in the current version: https://github.com/gogits/gogs/blob/f7b7d008b684a3475a1834b8b574e5ce082a723c/models/org.go#L218

But I have pushed a patch to `develop` which ignores invalid `org_user` records.
