### ISSUE TITLE
Feature: Commit linking to the issue (Issue creation fro commit)

### ISSUE THREAD

**Issue by yeleleo** [gogits/gogs#4308]
Hi All,

Got a feature request where you can add Issue to the commit, 
e.g. if you found a bug or UI fixes for this commit.
![2017-03-18 10-51-12 camera screen navigation d12f448531 - git service](https://cloud.githubusercontent.com/assets/1327411/24071092/b006d5fa-0bca-11e7-970f-1297c8be40e7.png)

Is there is any way you can do that?

**Comment by Unknwon** [comment]
Why can you just copy-paste the link to issue content?

There is no standard way of reporting issue from a commit.

**Comment by FibreFoX** [comment]
@yeleleo Better than creating some issue, I would suggest to create a pull-request, makes this less noise for the repository-maintainers. What is your use-case for this feature?

**Comment by yeleleo** [comment]
@FibreFoX report bugs from QA team and comments from product team

**Comment by FibreFoX** [comment]
Thats very interesting, makes me wonder about the whole process you have. QA team must have two ways to report bugs: 1. directly to some developer, 2. the issue-system from gogs.

What would be the leading system to track all the bugs? And why would these two ways need to being unified? And another question would arise: what about multiple commits being part of the same bug/issue?

Do you want to have these issues being part of some milestone or something like that to "generate a changelog"? (I'm asking, because I can't see some real benefit from it)
