### ISSUE TITLE
[feature request] Please obfuscate/encrypt Passwords in Config Files/Database

### ISSUE THREAD

**Issue by notes-jj** [gogits/gogs#4562]
Please implement a way to obfuscate the passwords in the config files.

### Current Behavior

The Passwords for MYSQL is stored in the /data/gogs/conf/app.ini and the Auth LDAP Connection Password is stored in the MYSQL Database in plain text.

### Desired Behavior

The Password is symmetrically encrypted (e.g. AES) with a key store in Gogs Source Code. That will just obfuscating the password for Gogs experts. But for any other person it will hide the password effectively.

The Password in the app.ini could have a semaphore, so that Gogs will encrypt the password if it finds an unencrypted one.

**Comment by skorokithakis** [comment]
This is security by obscurity, though, making you think that your password is secure while it's trivially readable by anyone with a small program...

**Comment by notes-jj** [comment]
@skorokithakis Yes it is, but it's better than having a plain text password in a text file with the label password right before and the user name right above it.

**Comment by lenovouser** [comment]
Nope it is not because it gives the normal user a feeling of security while it's trivial to decrypt for people who know what they are doing anyways.

**Comment by Unknwon** [comment]
Hi, thanks for the feedback!

However, if someone is targeting your Gogs instance for your MySQL password, the person already has the file system access and can easily get whatever key that is stored and used to encrypt/decrypt. And because Gogs is open source, everyone is potentially knowing what is the algorithm to encrypt/decrypt.

So... I suggest you fork and modify the corresponding source code to achieve the goal in OP.
