### ISSUE TITLE
Doesn't seem to work with git 2.14 (on windows)

### ISSUE THREAD

**Issue by tarioch** [gogits/gogs#4677]
- Gogs version (or commit ref): 0.11.28.0718
- Git version: server 2.1.4, client 2.14
- Operating system: server linux, client windows
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [ ] MySQL
  - [ ] MSSQL
  - [X] SQLite

## Description
After windows client was upgraded from 2.13.3 to 2.14 push/checkout/pull failed with:

Unregistered owner: upload-pack 'xyz

in the serv.log

Downgrading git to 2.13.3 fixes issue again

**Comment by josepho0918** [comment]
Same issue here

**Comment by whyb** [comment]
同样的问题发生在我的身上

**Comment by chevell** [comment]
Hi all,

I found this issue when investigating a similar problem in a different piece of software.

Can you run `set GIT_TRACE=1` and then re-run your failed git command?

It looks like the Windows client is requesting that the server run `git upload-pack` instead of `git-upload-pack`. You can enable git trace logging on Windows and *nix/macOS clients, and I suspect you'll find that only the Windows client asks the server to run `git upload-pack` with the space there.

Some upstream SCM hosts (e.g. GitHub) *do* support this syntax, but it's still strange that the Windows client is behaving inconsistently. It's possible this is a Git 2.14 Windows client bug, that some SCM hosts are successfully working around for internal reasons, and some are not.

**Comment by tarioch** [comment]
I can confirm the situation as described by @chevell

**Comment by tarioch** [comment]
See https://jira.atlassian.com/browse/BSERV-10013 that points out the commit in git

**Comment by chevell** [comment]
The maintainer of Git for Windows has reverted their change, which should correct this behaviour: https://github.com/git-for-windows/git/commit/0f3342804fc6fa558a7c9e220e7e9ab4c86e8226

It may still be worth supporting the `git upload-pack` / `git receive-pack` syntax style, since they *are* technically valid, but now that Git for Windows has been updated this specific report can probably be closed.

And with that, I'm out 🍃

**Comment by eshizhan** [comment]
Also have issue while clone repo.
```
$ git clone git@192.168.0.20:dev/test.git
Cloning into 'test'...
Gogs: Repository owner does not exist
fatal: Could not read from remote repository.
```
resolved by downgrading Git 2.13.3

**Comment by Brawl345** [comment]
Upgrade to Git 2.14.1, the issue was fixed there.

**Comment by SuriyaaKudoIsc** [comment]
@Unknwon Same issue here

**Comment by Unknwon** [comment]
@SuriyaaKudoIsc have you tried to upgrade newer version of Git >=2.14.1?

**Comment by SuriyaaKudoIsc** [comment]
@Unknwon I upgraded to **`git version 2.14.2.windows.3`**.

Now I get this error:

```
2017/10/14 15:43:38 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: do migrate: 
write hook file 'H:\GITSURIYAATK\gogs-repositories\dart-lang\sdk.git\hooks\pre-receive': 
open H:\GITSURIYAATK\gogs-repositories\dart-lang\sdk.git\hooks\pre-receive: 
Das System kann den angegebenen Pfad nicht finden.
```

*(PS: The German sentence `Das System kann den angegebenen Pfad nicht finden.` means `The system cannot find the indicated path`!)*

**Comment by Unknwon** [comment]
@SuriyaaKudoIsc that is completely different issue. Please file an formal issue report on GitHub to provide more information so I can help you better.
