### ISSUE TITLE
support binary data

### ISSUE THREAD

**Issue by gedw99** [gogits/gogs#484]
gogs is really great, because it is cross platform.

I was wondering if people like the idea of making it support binary data as part of the repo.
git annex, git fat are implemenation of this.
But they suffer from poor cross platform support and are hellish to work in a team environment.

gogs could really shine if it had this:
- all clients can manage binary and non binary. 
- the server can store the git repo and the binary data
- a one stop shop as they say.

This really would be great. what do people think ?
I am not fully sure of the level involved, but i dont think its that much with the framework that Gogs already has.

**Comment by FREEZX** [comment]
I personally need this feature.
I work in game development. Games have different sorts of non-textual assets that cannot be merged and are big: Music, textures, 3d models, compiled binaries, etc.
Git repositories grow very fast when these kind of files get added and get changed over time, because git is receiving their whole history when cloning the project.
For this reason game developers resort to other (very expensive) version control systems like perforce, plastic scm, etc., that are optimized for this kind of workflow.

The best solution with git is using annex to handle all binary files.

Refer to this walkthrough to read about how annex is used and remotes work:
https://git-annex.branchable.com/walkthrough/

**Comment by FREEZX** [comment]
Also, a closed issue on gitlab that discusses the issue and might provide some insight:
https://github.com/gitlabhq/gitlabhq/issues/13

**Comment by Unknwon** [comment]
All people please follow on https://github.com/gogits/gogs/issues/1322
