### ISSUE TITLE
Change domain?

### ISSUE THREAD

**Issue by karl0ss** [gogits/gogs#4957]
Hope someone can help..

I forgot to renew my domain, so have had to change it, I have updated the DOMAIN and ROOT_URL in the /custom/config/app.ini file

All the urls have updated and I can access my site, but I can't push to, or even clone a new repo, I get -
```

$ git clone http://kithub.tk:1337/Karl/TRepo.git
Initialized empty Git repository in c:/Users/Karl/Documents/TRepo/.git/
error: The requested URL returned error: 401 while accessing http://kithub.tk:1337/Karl/TRepo.git/info/refs

fatal: HTTP request failed

```
Hope someone can help with what is going on..

Thanks

Karl

**Comment by 4oo4** [comment]
So I just browsed to that URL, since the repo isn't public, you'll need to provide your username and password when doing the `clone` command, see this:
https://stackoverflow.com/questions/10054318/how-to-provide-username-and-password-when-run-git-clone-gitremote-git

Also, noticed that you're running an older version of Gogs and that you're not using SSL. For security's sake, you should set up Let's Encrypt for your domain and get Gogs updated, not doing so is asking for trouble. To help protect your privacy, it's also usually a good idea to redact the domain name for your server when posting things publicly.
