### ISSUE TITLE
gogits organisation should be more independent and have more people 

### ISSUE THREAD

**Issue by pananormalny** [gogits/gogs#5038]
Hello !

I would like to point out problem in gogits github organisation/project.
At the moment all of the PR's are stuck because @Unknwon is absent.
gogs in my opinion is quite popular project on GH and it does not make sense to be dependent on 2 people. We (as a community) should have better project management. 

- More people assigned to project for example (that's the main problem at the moment I would say)

Right now - i.e if bus hits @Unknwon or/and @0rax ... we will need another fork cause there will be no person to accept PR's etc. 

What are your opinions on that? I think this should be discussed... (I saw a https://discuss.gogs.io/) but on GH there will be better track of progress...

**Comment by dorianboulch** [comment]
Take a look at Gitea ;)

**Comment by appleboy** [comment]
You can see the Gitea: https://github.com/go-gitea/gitea

**Comment by Pofilo** [comment]
Switching from Gogs to Gitea (with latest version of Gogs) seems to be a bit hard (because of databases changes since 0.10 of Gogs).

If someone have an easy way to migrate from latest Gogs to Gitea, it would be appreciated.

The advantage of Gitea is that there is multiple maintainers, so if one is away for several months, it does not impact the development of Gitea. If today someone makes a pull request with a security patch, it won't be merged for weeks, months or maybe never :/

**Comment by Unknwon** [comment]
Hi there, thanks for your thoughts! But this not correct place to post non-technical discussions. :D
