### ISSUE TITLE
[...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: sync: Error 1115: Unknown character set: 'utf8mb4'

### ISSUE THREAD

**Issue by noobcoder1983** [gogits/gogs#5052]
- Gogs version (or commit ref): 0.11.34.1122
- Git version:  2.16.2
- Operating system: CentOS 6
- Database (use `[x]`):
  - [ ] PostgreSQL
  - [x] MySQL
  - [ ] MSSQL
  - [ ] SQLite
- Can you reproduce the bug at https://try.gogs.io:
  - [ ] Yes (provide example URL)
  - [x] No
  - [ ] Not relevant
- Log gist (usually found in `log/gogs.log`):

2018/02/17 00:13:14 [FATAL] [...gs/routes/install.go:66 GlobalInit()] Fail to initialize ORM engine: migrate: sync: Error 1115: Unknown character set: 'utf8mb4'
2018/02/17 00:13:15 [TRACE] Log Mode: File (Trace)
2018/02/17 00:13:15 [ INFO] Gogs: Go Git Service 0.11.34.1122
2018/02/17 00:13:15 [ INFO] Cache Service Enabled
2018/02/17 00:13:15 [ INFO] Session Service Enabled

## Description
Build with Google Go 1.10, nothing was changed in MySQL Database. After update from GO to 1.10 and to Git Version 2.16.2 the restart of the GOGS Service produced the above error message
...

**Comment by mtsinc1** [comment]
The mysql database version for CentOS 6 is version 5.1. A search on "utf8mb4" brings up a reference to MySQL version 5.5. It's likely that Gogs is using an encoding that's not available in the older version.

I'm seeing the same error and will try to install and migrate to a MySQL 5.5 server.

**Comment by noobcoder1983** [comment]
Ah ok thanks for testing and for your help. I cannot upgrade at my actual hoster to new CentOS 7, so I have to wait or search for another Git service, maybe cgit ;-)

**Comment by mtsinc1** [comment]
I'm not thrilled about being forced to use utf8mb4, since I don't really need that much character flexibility, and it's not as universal as the old UTF-8. However, short of modifying the current version of Gogs, the easier and next-best alternative is to use MySQL 5.5 or later.

Like you, I'm not that eager to embrace CentOS 7, but since I do have the option and some CentOS 7 VMs available, that was the quickest way to test and temporarily fix the issue.

You should be able to install MariaDB version 5.5 (and later) on CentOs 6, even though it's not supported by the CentOS repository. Just add a MariaDB repo to your Yum configuration:

https://mariadb.com/kb/en/library/yum/

**Comment by thigg** [comment]
Simple workaround: remove the 3 occurences of utf8mb4 in the repo, change it to plain utf8 and rebuild.
Worked perfectly for me.

It would be nice if gogs could handle that automatically. This charset seems to be the only thing which destroys the support for backwards compatibility.

**Comment by burzum** [comment]
Same issue here for me... Can we please get a backward compatibility fix...? 😞

**Comment by thigg** [comment]
@burzum I don't remember. But by searching the repository right now, I found:
1. ´scripts/mysql.sql´
2. ´models/models.go´
