### ISSUE TITLE
Archive files should be created with repository name folder

### ISSUE THREAD

**Issue by devel-pa** [gogits/gogs#518]
ZIP file and TAR.GZ file have to have a root folder named after the project.
Check an archive from Gogs and one from GitHub.
Thanks,
Paul

**Comment by julianscheel** [comment]
I'd like to second this request. Not having a root-folder in the tarballs makes them unusable in various buildsystems (like buildroot) which expect archives to have a proper root-node.

**Comment by Unknwon** [comment]
You can now test online at https://try.gogs.io

In order to make this change take effect for your instance:

1. Update to `develop` branch
2. Run `go get -u github.com/gogits/git-module` and recompile Gogs
3. Go to admin panel `/admin`, and run operation `Delete all repositories archives`
4. Download desired archives and check

**Comment by Unknwon** [comment]
Close as implemented.

**Comment by ralphtheninja** [comment]
@Unknwon Out of curiosity. Why is the `Delete all repositories archives` needed in the admin panel?

**Comment by Unknwon** [comment]
@ralphtheninja to save disk space... mainly for the purpose of demo server...
