### ISSUE TITLE
need `gogs restore` with `gogs dump` files.

### ISSUE THREAD

**Issue by chai2010** [gogits/gogs#648]
```
gogs export // export db info
gogs import // import exported db info 
```

**Comment by zacheryph** [comment]
Of what use are the dump files if there is no way to restore them?  I am finding myself trying to move my gogs install and running into this rut of having to manually backup the data and the database.

**Comment by bkcsoft** [comment]
PR #3109 is a WIP for `gogs restore`

**Comment by jcgruenhage** [comment]
What kind of a partial restore did you have in mind @bkcsoft? you mentioned it in your PR, do you mean which files to restore or being able to select only some repos, some users/organisations, parts of the config etc?

**Comment by bkcsoft** [comment]
@jcgruenhage That PR is on hold for now. But it restores everything in the dumped zip-file, and it does so stupidly (i.e. overwriting stuff that's already there). I use it for migrating docker-containers (instead of migrating volumes which is "hard"...), but like the PR states, if you run it on a **live** system, it **will break** so use with care...

**Comment by Unknwon** [comment]
Possible on `release/0.11` branch with `./gogs backup` and `./gogs restore`.

But backup DB always, as it's not largely tested right now.
