### ISSUE TITLE
private repo with public issues

### ISSUE THREAD

**Issue by Dennis-Smurf** [gogits/gogs#649]
Is it possible to allow issues to be public (or logged on) while repositories remain private?

**Comment by srvg** [comment]
Sounds related to #776

**Comment by tarioch** [comment]
Another use case is if you have non public source code but still want to provide a public issue tracker

**Comment by Twisterat57** [comment]
I would like to be able to share setup links on the wiki page of the projects (ie: we have a team that prepares our Windows CE devices with specific customer applications to be installed on it) and also with Sales team for example.

Sharing Wiki (read only) and issues (Read/Write) for specific teams would be nice:

Those teams should not have access to the source code, but only to the wiki (Read only) and maybe on the issues (Read and Write i guess). OK this is not a standard function but this should be awesome to use gogs as a release share platform also!

**Comment by pferraris** [comment]
Different permissions for Issues and Wiki would be great!

**Comment by BruinY** [comment]
Two years ago of demand, although no arrangement..Let a person feel very sorry

**Comment by BruinY** [comment]
Hope in the near future can solve, this is a very important feature, should need to obtain a higher priority than others, it leads to better reputation

**Comment by nmaas87** [comment]
That would be very useful!

**Comment by BruinY** [comment]
@Unknwon please in 0.10 milestone complete

**Comment by Unknwon** [comment]
@BruinY It is not as easy as switch a button or change a value in database, will consider.

**Comment by lunny** [comment]
So it needs to redisign repo's permissions.

**Comment by BruinY** [comment]
@lunny  the repo's permission in the redesign??

@Unknwon Gogs is good product, Hope to be able to attach importance to this problem, the strengthening of project management features, can make gogs more popular

**Comment by Unknwon** [comment]
Everybody thinks their needs are more important.

**Comment by BruinY** [comment]
Maybe, but I think to strengthen the function of project management, for gogs will be better, but you still have to decide

**Comment by strk** [comment]
See also #2157

**Comment by ITwrx** [comment]
first, let me say thanks for gogs. It looks very promising for my use case, especially assuming this is implemented.

imho, it would be ideal if permissions could be set thusly for any given repo:

read/write for wiki (public read, write by user, user group or all users)
read/write for issues (public read, write by user, user group or all users)
read/write for repo/code (public read, write by user, user group or all users)
same perms flexibility for any new major feature(where applicable)

People use these features for many different reasons. Access for the general public, all clients, groups of clients, coworkers, etc. User & group perms for each major feature should allow all reasonable scenarios. 

I also tend to agree with @BruinY that this is an important feature request as i think Gogs should have been designed with this as part of it's early infrastructure and thus warrants temporary suspension of work on any ancillary features that have been planned since. Though, i mean that to be constructive feedback and certainly understand how these things happen. Also, i don't know any Go so i won't be much help with actual code for the forseeable future. typical, right?  :)

Thanks

**Comment by Hypfer** [comment]
We could also make use of a feature like this. :+1:

**Comment by hsrzq** [comment]
Different permissions for Issues and Wiki would be great!
Repo is for RD, Issues is for QA, Wiki is for QA&PM, so we can work with only one system!
Issues和Wiki使用不同权限是非常有必要的一个功能。
这个研发就可以使用代码库，测试使用Issues，测试和产品使用Wiki，这样大家只需要一个这样的系统就够用了

**Comment by Unknwon** [comment]
Patch has pushed to fix this issue, please test on `develop` branch or https://try.gogs.io.

**Comment by Fastidious** [comment]
Wow, "good things come to those who wait." Thanks for all the good, and hard work @Unknwon!

**Comment by Twisterat57** [comment]
Nice job guys... but when repo is private and Wiki/Issues set to public, users can't see the repo neither on organisation, neither on repositories list or whatever (only if we give them a strict html link to issue page of the project) ... If we put them as collaborators, they can see it but they can also see the repository sources, clone, download... etc due to the default "Read" access of the user, which is the lower repository access
