### ISSUE TITLE
Disable Captcha for Internal Uses

### ISSUE THREAD

**Issue by jcrubino** [gogits/gogs#697]
How can captcha images tests be removed?

**Comment by vijairaj** [comment]
It would be nice if the option to enable/disable is available during installation. It can be enabled by default though.

- [x] Enable captcha

**Comment by Unknwon** [comment]
Hi @jcrubino and @vijairaj !

It is now possible to use config option `[service] DISABLE_CAPTCHA=true` on `develop` branch!

**Comment by vijairaj** [comment]
Tested the new option to disable captcha and it works great :+1: 
I have a couple of suggestions though:
  1. The current setting for captcha can be displayed in /admin/config
  2. Instead of the `DISABLE_CAPTCHA=true` we could have it as `ENABLE_CAPTCHA=false`. In my experience I have seen that having a mix of options like enable_xxx and disable_yyy causes a lot of code smell it becomes difficult to comprehend lines like `if ! config.disable_yyy`. Instead having all options in the form enable_something and setting it to true/false in the default config as appropriate makes the code consistent.

**Comment by Unknwon** [comment]
@vijairaj you're right!

Working on it...

**Comment by Unknwon** [comment]
Now, changed to `[service] ENABLE_CAPTCHA=true`, and admin panel as well.

**Comment by vijairaj** [comment]
Tested and looks good. How about providing this option during install, so that it would be super easy for the newbies?

**Comment by Unknwon** [comment]
@vijairaj added :blush:

**Comment by vijairaj** [comment]
Tested it on the installation page and works flawlessly. Excellent :+1:

**Comment by Unknwon** [comment]
@vijairaj thanks your confirmation!

Close as implemented.

**Comment by jcrubino** [comment]
Thanks everyone for the great work on this and Gogs as a whole

**Comment by Unknwon** [comment]
@jcrubino :wink:
