### ISSUE TITLE
Migrate Issues from Github

### ISSUE THREAD

**Issue by matt-h** [gogits/gogs#809]
Feature Request:
When migrating a repository from Github, it would be great if there was an option to migrate the Issues over as well.

**Comment by raichu** [comment]
Don't forget bitbucket and gitlab!

**Comment by Unknwon** [comment]
@raichu sure!

**Comment by fedelibre** [comment]
Another service to consider is **Google Code**, which went read-only last week. Many projects will need to import their issues.

I wished I found Gogs before.. An open source project I contribute to chose another software (Allura), which is able to import from Google Code.

**Comment by fedelibre** [comment]
Anyway, Google Code has an [Issue Exporter](https://code.google.com/p/support-tools/wiki/IssueExporterTool), which migrate to Github or Bitbucket. I've tested it on Bitbucket and it does a good job. The data dump is text only and the attachments are link to storage.googleapi.com. If Google doesn't delete these files this is a good compromise.

So if you don't develop a specific tool for Google Code, a 2-step migration would be an alternative.

**Comment by fedelibre** [comment]
BTW, Allura is the software behind **Sourceforge**, another service to be considered.

**Comment by Unknwon** [comment]
@fedelibre thanks your info!

**Comment by fedelibre** [comment]
@Unknwon Actually the exporter to bitbucket was not perfect: for example, labels are missing.
I'm now testing the export to github and I've asked to be whitelisted but it still takes some time due to the API rate limit of 5000 reqs/hour.

When you want to work on the importer, let me know if you need the json file of a Google Code project to see the structure of the json file and make a migration test.

**Comment by Unknwon** [comment]
@fedelibre 

> When you want to work on the importer, let me know if you need the json file of a Google Code project to see the structure of the json file and make a migration test.

It would be prefect!

So, Google Code exporter always gives a JSON, right?

**Comment by fedelibre** [comment]
You can download it from [here](https://www.dropbox.com/s/4cqzfhm31ke3ekq/lilypond-google-code-issues.json?dl=0).

Tthe data dump is made by Google Takeout. The file format depends on the service chosen and for Google Code there's only JSON, if I remember correctly. It dumps the data of any project you are an owner of. As I'm a member of a single project, there's only one (but lots of issues, more than 4000).

**Comment by Unknwon** [comment]
Thanks @fedelibre !

**Comment by fedelibre** [comment]
Let me add some comments on Google Code [Issue Exporter](https://code.google.com/p/support-tools/wiki/IssueExporterTool), in case someone might be interested in the 2-step migration for Gogs.

## Migration to Bitbucket

Repository: [lilyissues on bitbucket](https://bitbucket.org/fedelibre/lilyissues/issues?status=new&status=open)

*Pro*:

- all issues imported;
- issue IDs are kept;
- quick migration because attachments are not saved to bitbucket server, there's only a link to google servers.

*Con*:

- labels missing;
- attachments are on google servers;
- some links to attachments are broken.
 
## Migration to Github

Repository: [lilyissues on github](https://github.com/fedelibre/lilyissues/issues)

*Pro*:

- all issues imported;
- labels saved correctly;
- attachments are saved on github servers;
- the migration took 9 hours for a project of 4000 issues and several attachments (you need to be whitelisted by github team to speed up).

*Con*:

- issue IDs are different from original ones;
- some image attachments (stored on github server) are missing.

Overall I think that migration to Github is better than to Bitbucket.
But I hope that Gogs will have a better importer.

**Comment by Unknwon** [comment]
@fedelibre I've taked a look on Google's JSON, is there any docs describes every field?

**Comment by fedelibre** [comment]
I don't think so, I couldn't find anything

**Comment by Unknwon** [comment]
OK...

**Comment by Unknwon** [comment]
@fedelibre Where is the base URL of attachments?

**Comment by fedelibre** [comment]
In [this issue](https://code.google.com/p/lilypond/issues/detail?id=4559) I see this link:

https://lilypond.googlecode.com/issues/attachment?aid=45590000000&name=4559.preview.png&token=ABZ6GAcqKCIX6KkvBTPvPmD1fQt4wo99_Q%3A1441282628797&id=4559&inline=1

However this might not be the real place. If you take a look at [this issue imported in bitbucket](https://bitbucket.org/fedelibre/lilyissues/issues/4499/uniform-stretching-causes-bad-bar-line) I find this kind of link:

https://storage.googleapis.com/google-code-attachments/lilypond/issue-4499/comment-0/issue.png

Much better! This seems the real location and the format is clear.

**Comment by Unknwon** [comment]
Very helpful!

**Comment by xet7** [comment]
Hi,
to download GitHub issues, I tried
https://github.com/piwik/github-issues-mirror PHP Symfony command-line
based project that uses GitHub API to download issues as JSON files,
and has PHP-based viewer that has option to show for example 100
issues per page, number 100 is configurable setting. PHP viewer did
not show issue images, but JSON source code seems to have image URLs
pointing to GitHub under https://cloud.githubusercontent.com domain,
so with some script images could be downloaded and changed at source
code. Next steps would be to download images based on info from JSON
files, figure out in what format issues are at Gogs (probably look at
postgres database), and generate script to insert JSON and images as
Gogs repo issues.

But I don't know is this any better that other software some others suggested previously in this issue.

**Comment by Unknwon** [comment]
@xet7 thanks your info!

But I think it would be better to directly use GitHub APIs in Gogs.

**Comment by xet7** [comment]
Yes of course.
I don't know is there any other OpenSource software that already has feature to import GitHub issues.

And then, what about importing pull requests? Is there already issue about that?

BR,
xet7

**Comment by Unknwon** [comment]
@xet7 Pull Request will not be migrated as far as I think right now.

**Comment by mgracer48** [comment]
+1000

**Comment by cusspvz** [comment]
+1

**Comment by GameXG** [comment]
Team does not currently plan to provide import functions performed by gogs itself?
Since the existence of migrate function, it is recommended to provide through github, Bitbucket, gitlab import function.

issues whether to keep the original author information? gitlab import all responses will be merged into one, it does not feel good within each issues.
However, if the original author to retain new information that will be part of the problem.

**Comment by Unknwon** [comment]
Update: https://github.com/gogits/go-gogs-client/wiki/Issues

**Comment by herby** [comment]
It would be nice if I could have API to create issue closed / close it. In https://lolg.it/herby/gh2gogs I can import issues, but all of them are created open.

**Comment by Unknwon** [comment]
@herby good point, miss that!

**Comment by herby** [comment]
What is ETA on this (and do you think of API to create an issue closed, or to close it, or both)?

**Comment by Unknwon** [comment]
@herby please try on `develop` branch or https://try.gogs.io, you can use field `"closed": true` to set state to closed when create.

**Comment by herby** [comment]
无闻 wrote:
> @herby <https://github.com/herby> please try on |develop| branch or
> https://try.gogs.io, you can use field |"closed": true| to set state to
> closed when create.

Tried on try.gogs.io, it works, with maybe one gltich (as seen in 
attachment) - it shows "75 issues" in the badge but only 35 are open - 
bug or feature?

**Comment by herby** [comment]
Sorry, no attachment, as I sent the image in email. See https://try.gogs.io/herby/import to find the 75/35 discrepancy.

**Comment by Unknwon** [comment]
@herby thanks! This is indeed a bug!

**Comment by Unknwon** [comment]
@herby `develop` branch and demo site are now correct!

It corrects all wrong count at start, so you don't need to do anything to fix old values.

**Comment by mathwhiz1212** [comment]
So, how do I import issues from a github repo to a repo in gogs?

**Comment by Unknwon** [comment]
@mathwhiz1212 you would have to write a script and call API...

**Comment by mathwhiz1212** [comment]
@Unknwon That's over my head. I'll wait until it gets implemented.
