### ISSUE TITLE
How to migrate git repositories to gogs?

### ISSUE THREAD

**Issue by wanghm** [gogits/gogs#881]
We have a git server with over 200 repositories, Only ssh protocol is supported now.
I just setup gogs server, and want to migrate the repositories to gogs.
Can you please tell me how to do this?

I check migration feature of gogs, it seems like the source repositories must be access by http(s).

**Comment by Unknwon** [comment]
Hmm..? Why did you close the issue?

**Comment by wanghm** [comment]
Just wondered if here is for QA. 
Appreciate it if someone can answer me.

**Comment by Unknwon** [comment]
Sure, currently Gogs only supports HTTP/HTTPS clone because it can be done directly through web interface.

It is possible to add support for clone by SSH, but requires user to do something like generate a public key for the server that runs Gogs, and have correct permission on remote SSH server. Then, when Gogs do `git clone ...` will be successful.

You can turn this into a feature request if that's what you wish to.

**Comment by wanghm** [comment]
Thanks, it' not important.
I can do migration by other ways(create repositories and copy directories)

**Comment by Unknwon** [comment]
@wanghm no problem!

**Comment by renard** [comment]
This topic is quite old but it might interest some people.

Obviously migrating a few repositories is pretty straightforward, you can clone and push them.

Is there a procedure to migrate more than just repositories, such as messages, PR, issues, credentials etc.?

Thanks

**Comment by jucajuca** [comment]
I recently migrated my repositories. I just copied the data folder and the DB to a new server. Then you need to run these two actions:

Rewrite '.ssh/authorized_keys' file (caution: non-Gogs keys will be lost) 
Resync pre-receive, update and post-receive hooks of all repositories 

It was one of the easiest migrations so far.
