### ISSUE TITLE
Optionally do not verify certificate for hooks

### ISSUE THREAD

**Issue by ripienaar** [gogits/gogs#891]
When sending a hook to a https server and the server has a self signed cert you get:

```
2015/02/02 11:33:21 [session.go:969 Iterate()] [E] Delivery: Post https://wiki.internal/hooks/gogs: x509: certificate signed by unknown authority
```

It's common for internal services to not have valid certs - they can be on made up domains like .local as above or its just not needed for internal use, company have policies of having to use internal CAs etc so buying a cert is sometimes not an option.  It also seems the client does not properly parse chained certs so even some totally valid purchased certs is not usable by gogs as hook recipients.

It would be good if the hook HTTPS client can optionally disable SSL validation.  this is not about the certs installed into gogs it's about the services it would connect to when sending a hook.

**Comment by Unknwon** [comment]
Thanks your report! I'll look into it.

**Comment by EtienneBruines** [comment]
@ripienaar Doesn't really sound like best practice use.
Usually one would (A) start its own certificate authority - and import those into servers, to say "you can trust certificates signed by me", or (B) import each and every certificate at each server its connecting with (easier with fewer servers). 

Even though there's no 3rd party available, it would make sense to make sure the local certificates are trusted. 

http://kb.kerio.com/product/kerio-connect/server-configuration/ssl-certificates/adding-trusted-root-certificates-to-the-server-1605.html

http://askubuntu.com/a/94861/244492

As to the properly chained certs: the certificates should be concatenated in an exact matter (no newlines in between the certificates, for example). Most of the time browsers will accept it, but Go won't. It will be your worth while to fix this, because quite some mobile devices won't connect either. This is usually the case with the cheaper certificates.

**Comment by ripienaar** [comment]
For an internal wiki server, I luckily care nothing about mobile browsers :) chained certs that are accepted  browsers today isn't accepted by go, that's not really my problem, sounds like a issue with go tbh.

github has a tick box per hook to disable verification, I assume they've given up hoping the whole world will follow best practises. I have 3rd parties that just aren't interested in changing their stuff - yes, they are not technically correct, or rfc compliant or whatever, but its real life not technical nirvana world and a tool like this should be realistic.

**Comment by EtienneBruines** [comment]
Fair point.

**Comment by Unknwon** [comment]
Just made a push on `dev` branch to use `[webhook] ALLOW_INSECURE_CERTIFICATION = true`.

**Comment by phsmit** [comment]
@Unknwon Wouldn't it be better to call it "SKIP_VERIFY", just as with the mailer? Or SKIP_TLS_VERIFY?

**Comment by Unknwon** [comment]
@phsmit your one is much shorter, I like it!

**Comment by Unknwon** [comment]
New code pushed.

**Comment by Unknwon** [comment]
As new mirror release `v0.5.13` is going to release, and this issue is labeled as **feedback needed**, so close it for **assumed resolved**, feel free to reopen this if you want to continue discussing. :beer:

**Comment by ripienaar** [comment]
I tested this and can confirm it works, thanks a lot for the quick turn around

**Comment by jeevarathinam-dhanapal** [comment]
Can services also have the "skip ssl verification" checkbox just like webhooks?

**Comment by lunny** [comment]
Skiping ssl verification is your git client's setting.

**Comment by tobiashochguertel** [comment]
Works great ;)

**Comment by sunshine69** [comment]
In my case it fails even I have correct certificate (not self signed) and the web browser show no error to the port url.
