### ISSUE TITLE
Issue: pagination

### ISSUE THREAD

**Issue by EtienneBruines** [gogits/gogs#932]
Only a limited amount of issues is shown (20 at the moment) - but sometimes you want to view more than just the given amount.

As I noticed in the comment below, there is some pagination in the back-end already. It's just not implemented in the UI yet (dev branch of last week). This would be nice to have.

**Comment by EtienneBruines** [comment]
I see something that indicates pagination in `models/issue.go`, lines `193` and `194`. 
In `repo/issue.go`, lines `97` and `100` parse the `page` parameter from the URL. 

Manually adding `?page=2` to the URL works. 

Updated original post accordingly.

**Comment by Unknwon** [comment]
Thanks for the report! Will fix this along with new issue UI.

**Comment by Unknwon** [comment]
Should be fixed in latest `develop` branch and can be tested here: https://try.gogs.io/unknwon/gogs/issues

**Comment by manfer** [comment]
Could you please create more than 20 issues (a few tens would be even better to test large issue queues) on the test site just to see if the pagination is full pagination and not just a previous/next page link?

If it is just only previous/next page links I would say it is not a good idea to close this issue.

In my opinion pagination should be prepared for large issue queues with an easy way to jump several pages at a time.

And a way to decide the number of issues per page, to jump to last page, and to jump to first page would be helpful too though these would be less important and optional.

If it is not a full pagination already sooner or later you will have a new issue in gogs about the pagination usability not being good enough.

By the way, if possible a reference to the commit that solves issues instead of a reference to a full branch would be helpful to look at the code.

**Comment by Unknwon** [comment]
Hi @manfer , thanks your feedback!

> see if the pagination is full pagination and not just a previous/next page link?

Not sure what do you mean? Test site right now has 11 issues total and show 10 each page. 

Agree to other points, but closed issue is because solved what issue describes, and it's true that you can create another issue about pagination usability.
