### ISSUE TITLE
gogs能不能添加插件功能

### ISSUE THREAD

**Issue by CaiCQ** [gogits/gogs#991]
我希望添加一些针对性的功能，不知道能不能提供插件形式接入，不想每次都修改项目代码，例如可以在菜单栏添加特定按钮，在某些处理时候添加事件等

**Comment by Unknwon** [comment]
Thanks your feedback!

Kind of related to https://github.com/gogits/gogs/issues/854 (almost same feature request). 

Plugin is a huge topic, based on what you want to do, we need to define how you are able to do it.

It's hard to explain in few words or implement it in few lines of code, otherwise it will become a mess.

We can leave this as a feature request but most likely is not happening in the near future. :bowtie:

**Comment by Unknwon** [comment]
Please follow on https://github.com/gogits/gogs/issues/854
